### ISSUE TITLE
Eliminate or reduce the requirement to put Namespace and register in every file.

### ISSUE THREAD

**Issue by samreid** [phetsims/phet-core#100]
In https://github.com/phetsims/tasks/issues/378 we introduced Namespace as a standard pattern to register most/all files with a global namespace.  Today when @zepumph asked how TypeScript would deal with types for those globals, I replied:

> To specify the type for a global, it seems the convention is to add a type in the ambient types file.  This could presumably be done for phetioEngine.

But it raised a larger discussion about the need for Namespace/register everywhere.  In circuit-construction-kit-common, there are 105 namespace import and register calls which, to my knowledge, have never been used.  Whenever I create/rename a file I have to deal with this overhead.  I do not use globals or dev tools in a way that leverages Namespace at all.  I proposed an alternate for when devs need to access code in the dev tools, based on recommendations in https://stackoverflow.com/questions/52569996/how-to-use-es6-modules-from-dev-tools-console.

One alternative would be to add a macro in the IDE that copy/pastes a line that lets you access that file in the dev tools.  Like, if I wanted to access EmphasizedHarmonics in the devtools, I would navigate to that file in the IDE, press a keystroke to get this clipboard text, then I would paste in the dev tools:

```
var EmphasizedHarmonics = (await import('../chipper/dist/js/fourier-making-waves/js/common/model/EmphasizedHarmonics.js')).default;
```

Last we discussed, it seemed like lots of developers were using namespace in the dev tools all the time, so the effort was warranted.  We also did not have ideas for alternatives like this.  So when it’s time, I’d like to double check on all that.

This is a very busy quarter, so we maybe should discuss when our time frees up.  But even moving to developer-preference on whether sim-specific repos use namespace/register would be an improvement in my opinion.

**Comment by pixelzoom** [comment]
>  Whenever I create/rename a file I have to deal with this overhead.

I'd like to understand why there's overhead, and whether it's really significant.   Creation of the Namespace instance (e.g. molarity.js) is handled by `grunt create-sim`.  Adding `register` calls when .js/.ts files are created should be handled by making that part of the your WebStorm Live Template for new files.  And renaming a class should presumably also rename its the `register` args without additional overhead. Personally, I experience near-zero overhead.

**Comment by samreid** [comment]
I recently experienced this overhead when converting to the proposed enumeration pattern.  When copy/pasting a pre-existing file from another repo, then I have to adjust the import and register statement.  It happened enough times and took long enough to be a bother.

> Creation of the Namespace instance (e.g. molarity.js) is handled by grunt create-sim

I have not experienced significant slowdown in that part.

> And renaming a class should presumably also rename the register args without additional overhead.

That's true, renaming incurs little overhead for this.

> Adding register calls when new files are created can (should!) be handled by making that part of the your WebStorm Live Template for new .js/.ts files.

I have not been using a template for file creation recently. More often (recently), I will copy from a related file or start from scratch. I wouldn't want to have to use a template primarily to add boilerplate code that will never be used.

**Comment by samreid** [comment]
After the decision in https://github.com/phetsims/phet-info/issues/184#issuecomment-1050162689, we are able to export classes inline, like:

```ts
export default class DotPlotNode extends Node {
  // ...
}
```

To me, this makes the register call feel even more out-of-place and unnecessary.  I'm ready for more discussion on this topic.  One decision could be that we decide to keep register calls is certain common code repos, or in sim repos at the developer's discretion, but not require them everywhere.

@chrisklus and I also tested other ways to load modules in the dev tools, and this worked OK:

```ts
var Vector2 = (await import('../chipper/dist/js/dot/js/Vector2.js')).default;
```

We could add a convenience call around it like `var Vector2 = await phetImport('dot/Vector2');` if desired.

**Comment by chrisklus** [comment]
I also experience a little bit of overhead with registering and would prefer to omit it if not needed. I don't really use types as @samreid demonstrated above with `Vector2`, but I do like to control parts of the sim like:

`phet.joist.sim.screenProperty.value.view.resetAllButton.visibleProperty.value = false;`

But it seems like that is largely relying on things already on the prototype, not registration? at least from `sim` onward.

**Comment by zepumph** [comment]
Happy to go with whatever the team decides. I don't use them a ton, and perhaps not enough to warrant everyone adding them everywhere, but it is really nice to have everything available from the command line. I guess I find myself really only using it for debugging and investigation. I know that common code libraries that are built rely on it, see something like  https://github.com/phetsims/axon/blob/5e39e13f97fb6cafd5a8019779dfcec75cb9d2dd/js/main.js. Also the scenery playground is totally set up to be used via Namespace.

Also PhET-iO is completely dependent on the namespace for production code. 

Perhaps we should make a lint rule to require it in choice common code repos? And devs can add their sims to it if they so choose.

**Comment by zepumph** [comment]
@jonathanolson was a large proponent of this, let's wait to discuss until he is present.

**Comment by pixelzoom** [comment]
I use this feature regularly (every other week?) to put together "minimum examples" when reporting problems, for example see https://github.com/phetsims/scenery/issues/1359#issuecomment-1040769775.  Most often I'm instantiating somethng in axon, dot, kite, or scenery.  I'm not sure how I'd do that without namespace registration. And if we're concerned about overhead, I certainly shouldn't be expect to add it to files when I need it. 

I still haven't heard what the overhead is. If you're using a WebStorm Live Template, or even copying an existing file, naming (or re-naming) the class should also change the arguments to `register`.

Is there really a problem with overhead? Or is it just that you don't like to see the `register` call at the bottom of each file?

**Comment by samreid** [comment]
> I use this feature regularly (every other week?) to put together "minimum examples" when reporting problems, for example see https://github.com/phetsims/scenery/issues/1359#issuecomment-1040769775. Most often I'm instantiating somethng in axon, dot, kite, or scenery. I'm not sure how I'd do that without namespace registration.

Yes, as described in https://github.com/phetsims/phet-core/issues/100#issuecomment-1087993162, we could keep register calls in certain repos.

> I'm not sure how I'd do that without namespace registration. 

In https://github.com/phetsims/phet-core/issues/100#issuecomment-1087993162 it was described how an `await import` can access any module in code without any namespace registration.

> Most often I'm instantiating somethng in axon, dot, kite, or scenery.

How many times would you say that you've instantiated any of the 114 registered objects in Geometric Optics?  Or any of the 115 registered objects in Circuit Construction Kit?

> And if we're concerned about overhead, I certainly shouldn't be expect to add it to files when I need it.

I agree we would not want to add those as needed.

> I still haven't heard what the overhead is.

That was reported in https://github.com/phetsims/phet-core/issues/100#issuecomment-1026111651.  "It happened enough times and took long enough to be a bother."

> If you're using a WebStorm Live Template, 

As mentioned in https://github.com/phetsims/phet-core/issues/100#issuecomment-1026111651, I am not using that.

> or even copying an existing file, naming (or re-naming) the class should also change the arguments to register, with zero additional effort.

Yes, but if you copy code from another repo, you have to import the different namespace.

> Is there really a problem with overhead?

Yes, "It happened enough times and took long enough to be a bother."  Otherwise I wouldn't have mentioned it.

> Or is it just that you don't like to see the register call at the bottom of each file?

Yes, it feels like (in the case of Circuit Construction Kit), 115 lines of code that will never be useful.  I don't like to see useless code at the bottom of each file.

**Comment by jessegreenberg** [comment]
Some discussion notes from today:

JO: We don't need namespace to get around circular dependencies. So I am OK removing this.
CM/MK: There are circular dependencies still.
JO: You can get around this with a different project structure.

MK: Why should we eagerly try to get rid of them?

KP: This does not seem like an urgent issue relative to other priorities (like TypeScript).
SR/CK: What about leaving existing usages but making the requirement more relaxed?

Decision: Lets keep it as is for now, when there is less churn in common code we can reconsider this.

**Comment by samreid** [comment]
Perhaps one easy step would be for @samreid to remove all namespace calls in a sim and see if there are any problems or not?  Once our time frees up from more important things.

**Comment by samreid** [comment]
Using this patch, I searched for files that `export default` and declare a `class` but do not `register` anything.

<details>

```diff

Index: eslint/rules/copyright.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/eslint/rules/copyright.js b/eslint/rules/copyright.js
--- a/eslint/rules/copyright.js	(revision e69d81c0c05c1c670153a63ce69cda2335d1e6ef)
+++ b/eslint/rules/copyright.js	(date 1659538672934)
@@ -18,6 +18,16 @@
       // Get the whole source code, not for node only.
       const comments = context.getSourceCode().getAllComments();
 
+      const text = context.getSourceCode().text;
+
+      if ( text.includes( 'export default' ) && text.includes( 'class ' ) && !text.includes( '.register(' ) ) {
+        context.report( {
+          node: node,
+          loc: 1,
+          message: 'Missing namespace registry'
+        } );
+      }
+
       if ( !comments || comments.length === 0 ) {
         context.report( {
           node: node,

```

</details>

It reported the following cases:

```
~/apache-document-root/main/perennial-alias$ grunt lint-everything --disable-eslint-cache
Running "lint-everything" task
[........................................] 100.00%

aqua/js/CTQIconNode.ts
axon/js/EnumerationProperty.ts
axon/js/StringEnumerationProperty.ts
bending-light/js/intro/view/AngleTextView.ts
bending-light/js/more-tools/model/Probe.ts
circuit-construction-kit-common/js/model/PowerDissipatedProperty.ts
circuit-construction-kit-common/js/model/analysis/LTAResistiveBattery.ts
circuit-construction-kit-common/js/model/analysis/LTAState.ts
greenhouse-effect/js/common/PhotonSprites.ts
models-of-the-hydrogen-atom/js/common/model/ProbabilisticChooser.ts
nitroglycerin/js/demo/MoleculesScreenView.ts
nitroglycerin/js/nodes/MoleculeNode.ts
phet-core/js/types/PickOptional.ts
phet-core/js/types/PickRequired.ts
phet-io-wrappers/common/js/Client.ts
phet-io-wrappers/common/js/CredentialsDialog.tsx
phet-io-wrappers/common/js/StandardPhetioWrapper.ts
phet-io-wrappers/common/js/migration/Command.ts
phet-io-wrappers/common/js/migration/LinkedElementConversionDelete.ts
phet-io-wrappers/common/js/migration/LinkedElementHasElementID.ts
phet-io-wrappers/common/js/migration/MigrationEngine.ts
phet-io-wrappers/common/js/migration/PhetioTypeDelete.ts
phet-io-wrappers/common/js/migration/TandemFragmentRenamed.ts
quake/www/js/EnhancedVibration.js
quake/www/js/ParameterSlider.js
quake/www/js/ScreenDebugLogger.js
quake/www/js/VibrationPattern.js
quake/www/js/VibrationPatternDisplay.js
ratio-and-proportion/js/common/model/RatioTerm.ts
ratio-and-proportion/js/common/view/CueDisplay.ts
ratio-and-proportion/js/common/view/describers/RatioInputModality.ts
scenery-phet/js/TimeSpeedRadioButtonGroup.ts
scenery-phet/js/demo/components/demoFlowBox.js
scenery-phet/js/demo/components/demoGridBox.js
scenery-phet/js/demo/components/demoParametricSpringNode.ts
scenery-phet/js/demo/components/demoScientificNotationNode.ts
scenery-phet/js/demo/components/demoSpinningIndicatorNode.ts
studio/js/PhetioElement.js
studio/js/PhetioElementView.js
studio/js/RootTreeNode.js
studio/js/Search.js
studio/js/Select.js
studio/js/StandardPhetioWrapperHandler.js
studio/js/TreeNode.js
studio/js/TypesHandler.js
studio/js/studio.js
studio/js/studioFuzz.js
tambo/js/WrappedAudioBuffer.ts
vegas/js/demo/components/demoLevelSelectionButton.ts
vegas/js/demo/components/demoLevelSelectionButtonGroup.ts
vegas/js/demo/components/demoRewardNode.ts
```

I suspect there are others, but these were easy to detect.  As far as I know, these missing register statements haven't been causing any problems for anyone.

**Comment by samreid** [comment]
Discovered during https://github.com/phetsims/mean-share-and-balance/issues/52, @marlitas and I were wondering if we can re-evaluate this now.

**Comment by samreid** [comment]
I removed from the project board for now--would prefer to discuss in a future week.

**Comment by samreid** [comment]
On second thought, any day is fine.  Here are some notes:

> If you feel like it's worth the time to find all the places were a Namespace is required (I doubt it),

How about we leave the common code ones?  Then we can avoid that investigation.

> [if] you think this will be a net savings (I doubt it)

Lines with namespaces can be deleted quickly with a regular expression, so it would only need to save me a few minutes to be a net gain.

> you don't mind the inconsistency across files

I don't mind.

**Comment by samreid** [comment]
Here's a regex that removes imports and namespace registrations from CCK-common (run it from the js/ directory).  Works on macOS, but I'm not sure if it is cross-platform.

`find . -type f -print0 | xargs -0 sed -i '' '/.*circuitConstructionKitCommon\..*$/d'`

I'd prefer to remove the namespace registrations from circuit-construction-kit-common unless someone really needs them.

**Comment by jonathanolson** [comment]
> In https://github.com/phetsims/phet-core/issues/100#issuecomment-1087993162 it was described how an await import can access any module in code without any namespace registration.

That doesn't work for built versions. It also cuts down on compatibility and usefulness of puppeteerEvaluate() used to check things in maintenance branches. Having access to a ton of common code through namespaces makes it significantly easier to test things or automatically filter "which sims need patches".

Perhaps we could investigate if webpack can provide us with a map of modules so we could look up similar things without namespaces for built versions?

Removing namespaces from most things will be a net negative for me, but I understand if there are net positives overall for the project.

**Comment by samreid** [comment]
Here is a primitive lint rule that detects files that have `export default class ...` but are missing `namespace.register` calls:

<details>

```diff

Subject: [PATCH] note
---
Index: eslint/.eslintrc.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/eslint/.eslintrc.js b/eslint/.eslintrc.js
--- a/eslint/.eslintrc.js	(revision 15258550c3ffc9e4e81c0bac5e5305f16885f8de)
+++ b/eslint/.eslintrc.js	(date 1670475087869)
@@ -1464,7 +1464,9 @@
     'no-spaced-func': 'error',
 
     // a default import variable name should be the same as the filename
-    'default-import-match-filename': 'error'
+    'default-import-match-filename': 'error',
+
+    'files-with-default-export-class-should-register-namespace': 'error'
     ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
   },
   env: {
Index: eslint/rules/files-with-default-export-class-should-register-namespace.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/eslint/rules/files-with-default-export-class-should-register-namespace.js b/eslint/rules/files-with-default-export-class-should-register-namespace.js
new file mode 100644
--- /dev/null	(date 1670475350388)
+++ b/eslint/rules/files-with-default-export-class-should-register-namespace.js	(date 1670475350388)
@@ -0,0 +1,96 @@
+// Copyright 2020, University of Colorado Boulder
+/**
+ * @fileoverview Rule to check for usages of namespace.register( key, value ) to enforce that the key and value match.
+ * One exception to this rule is when a function is added directly to the namespace. This is valid and useful
+ * particularly in common libraries like dot and scenery.
+ *
+ * Note that this rule looks for ANY CallExpression whose first argument is a Literal node and whose second
+ * argument is an Identifier node. So it will test any usage of register(), even if it isn't called
+ * on a namespace. There is no way for the rule to determine if the type of the CallExpression.object is a Namespace,
+ * so it cannot be more exclusive.
+ *
+ * The line namespace.register( 'ClassName', ClassName ) will have an AST node that looks like
+ *{
+ *   "type": "CallExpression",
+ *   "callee": {
+ *     "type": "MemberExpression",
+ *     "object": {
+ *       "type": "Identifier",
+ *       "name": "namespace",
+ *     },
+ *     "property": {
+ *       "type": "Identifier",
+ *       "name": "register",
+ *     },
+ *   },
+ *   "arguments": [
+ *     {
+ *       "type": "Literal",
+ *       "value": "ClassName",
+ *       "raw": "'ClassName'",
+ *     },
+ *     {
+ *       "type": "Identifier",
+ *       "name": "ClassName",
+ *     }
+ *   ]
+ * }
+ *
+ * @author Jesse Greenberg (PhET Interactive Simulations)
+ * @copyright 2020 University of Colorado Boulder
+ */
+
+
+//------------------------------------------------------------------------------
+// Rule Definition
+//------------------------------------------------------------------------------
+
+module.exports = function( context ) {
+  return {
+    Program: node => {
+      const sourceCode = context.getSourceCode();
+      // const codeTokens = sourceCode.getTokens( node );
+      // const codeLines = sourceCode.lines;
+      const text = sourceCode.text;
+
+      if ( text.includes( 'export default class' ) ) {
+        if ( !text.includes( '.register( \'' ) ) {
+          context.report( {
+            node: node,
+            loc: node.loc,
+            message: 'File default exports a class but has no namespace registration'
+          } );
+        }
+      }
+
+      // console.log( 'hello' );
+      // if ( node.callee && node.callee.type === 'MemberExpression' ) {
+      //   if ( node.callee.property.name === 'register' ) {
+      //     const registerArgs = node.arguments;
+      //     if ( registerArgs.length === 2 ) {
+      //       const firstArg = registerArgs[ 0 ];
+      //       const secondArg = registerArgs[ 1 ];
+      //
+      //       // we allow adding functions directly to the namespace
+      //       if ( firstArg.type === 'Literal' && secondArg.type === 'Identifier' ) {
+      //         const firstArgValue = firstArg.value; // string from the Literal node value
+      //         const secondArgName = secondArg.name; // string from the Identifier node name
+      //
+      //         if ( firstArgValue !== secondArgName ) {
+      //           context.report( {
+      //             node: node,
+      //             loc: node.loc,
+      //             message: `namespace key must match value - key: ${firstArgValue}, value: ${secondArgName}`
+      //           } );
+      //         }
+      //       }
+      //     }
+      //   }
+      // }
+    }
+  };
+};
+
+module.exports.schema = [
+  // JSON Schema for rule options goes here
+];
\ No newline at end of file

```

</details>

Note it is very primitive and does not detect our older form of `class X{}... export default X`.  Nor does it check if the register call matches the default export name.  But here is the list of 30 files it detected that are not registered with a namespace (several are common code). Note there are classes in axon, scenery-phet, joist and sun that do not have namespace registrations.

<details>

```
All results (repeated from above)



/Users/samreid/apache-document-root/main/axon/js/EnumerationProperty.ts
  9:1  error  File default exports a class but has no namespace registration  files-with-default-export-class-should-register-namespace

/Users/samreid/apache-document-root/main/beers-law-lab/js/beerslaw/model/ATDetectorMode.ts
  11:1  error  File default exports a class but has no namespace registration  files-with-default-export-class-should-register-namespace

/Users/samreid/apache-document-root/main/beers-law-lab/js/beerslaw/model/LightMode.ts
  11:1  error  File default exports a class but has no namespace registration  files-with-default-export-class-should-register-namespace

/Users/samreid/apache-document-root/main/beers-law-lab/js/concentration/model/SoluteForm.ts
  11:1  error  File default exports a class but has no namespace registration  files-with-default-export-class-should-register-namespace

/Users/samreid/apache-document-root/main/circuit-construction-kit-common/js/model/PowerDissipatedProperty.ts
  6:1  error  File default exports a class but has no namespace registration  files-with-default-export-class-should-register-namespace

/Users/samreid/apache-document-root/main/circuit-construction-kit-common/js/model/analysis/LTAState.ts
  2:1  error  File default exports a class but has no namespace registration  files-with-default-export-class-should-register-namespace

/Users/samreid/apache-document-root/main/equality-explorer/js/common/model/UniversalOperator.ts
  9:1  error  File default exports a class but has no namespace registration  files-with-default-export-class-should-register-namespace

/Users/samreid/apache-document-root/main/joist/js/DynamicStringTest.ts
  3:1  error  File default exports a class but has no namespace registration  files-with-default-export-class-should-register-namespace

/Users/samreid/apache-document-root/main/joist/js/preferences/CharacterSet.ts
  10:1  error  File default exports a class but has no namespace registration  files-with-default-export-class-should-register-namespace

/Users/samreid/apache-document-root/main/models-of-the-hydrogen-atom/js/common/model/ProbabilisticChooser.ts
  9:1  error  File default exports a class but has no namespace registration  files-with-default-export-class-should-register-namespace

/Users/samreid/apache-document-root/main/natural-selection/js/common/view/pedigree/AlleleNode.ts
  11:1  error  File default exports a class but has no namespace registration  files-with-default-export-class-should-register-namespace

/Users/samreid/apache-document-root/main/nitroglycerin/js/demo/MoleculesScreenView.ts
  9:1  error  File default exports a class but has no namespace registration  files-with-default-export-class-should-register-namespace

/Users/samreid/apache-document-root/main/nitroglycerin/js/nodes/MoleculeNode.ts
  9:1  error  File default exports a class but has no namespace registration  files-with-default-export-class-should-register-namespace

/Users/samreid/apache-document-root/main/ph-scale/js/common/view/graph/GraphScale.ts
  3:1  error  File default exports a class but has no namespace registration  files-with-default-export-class-should-register-namespace

/Users/samreid/apache-document-root/main/ph-scale/js/common/view/graph/GraphUnits.ts
  3:1  error  File default exports a class but has no namespace registration  files-with-default-export-class-should-register-namespace

/Users/samreid/apache-document-root/main/phet-io-wrappers/common/js/CredentialsDialog.tsx
  6:1  error  File default exports a class but has no namespace registration  files-with-default-export-class-should-register-namespace

/Users/samreid/apache-document-root/main/phet-io-wrappers/common/js/StandardPhetioWrapper.ts
  18:1  error  File default exports a class but has no namespace registration  files-with-default-export-class-should-register-namespace

/Users/samreid/apache-document-root/main/phet-io-wrappers/common/js/migration/AddStateElement.ts
  12:1  error  File default exports a class but has no namespace registration  files-with-default-export-class-should-register-namespace

/Users/samreid/apache-document-root/main/phet-io-wrappers/common/js/migration/Command.ts
  12:1  error  File default exports a class but has no namespace registration  files-with-default-export-class-should-register-namespace

/Users/samreid/apache-document-root/main/phet-io-wrappers/common/js/migration/LinkedElementConversionDelete.ts
  13:1  error  File default exports a class but has no namespace registration  files-with-default-export-class-should-register-namespace

/Users/samreid/apache-document-root/main/phet-io-wrappers/common/js/migration/LinkedElementHasElementID.ts
  12:1  error  File default exports a class but has no namespace registration  files-with-default-export-class-should-register-namespace

/Users/samreid/apache-document-root/main/phet-io-wrappers/common/js/migration/MigrationEngine.ts
  14:1  error  File default exports a class but has no namespace registration  files-with-default-export-class-should-register-namespace

/Users/samreid/apache-document-root/main/phet-io-wrappers/common/js/migration/NumberPropertyNullRangeIsInfinite.ts
  12:1  error  File default exports a class but has no namespace registration  files-with-default-export-class-should-register-namespace

/Users/samreid/apache-document-root/main/phet-io-wrappers/common/js/migration/PhetioTypeDelete.ts
  13:1  error  File default exports a class but has no namespace registration  files-with-default-export-class-should-register-namespace

/Users/samreid/apache-document-root/main/phet-io-wrappers/common/js/migration/TandemFragmentDelete.ts
  13:1  error  File default exports a class but has no namespace registration  files-with-default-export-class-should-register-namespace

/Users/samreid/apache-document-root/main/phet-io-wrappers/common/js/migration/TandemFragmentRenamed.ts
  14:1  error  File default exports a class but has no namespace registration  files-with-default-export-class-should-register-namespace

/Users/samreid/apache-document-root/main/scenery-phet/js/GridIcon.ts
  9:1  error  File default exports a class but has no namespace registration  files-with-default-export-class-should-register-namespace

/Users/samreid/apache-document-root/main/scenery-phet/js/TimeSpeedRadioButtonGroup.ts
  13:1  error  File default exports a class but has no namespace registration  files-with-default-export-class-should-register-namespace

/Users/samreid/apache-document-root/main/scenery-phet/js/buttons/CameraButton.ts
  9:1  error  File default exports a class but has no namespace registration  files-with-default-export-class-should-register-namespace

/Users/samreid/apache-document-root/main/sun/js/SliderTick.ts
  10:1  error  File default exports a class but has no namespace registration  files-with-default-export-class-should-register-namespace

✖ 30 problems (30 errors, 0 warnings)


Fatal error: Lint failed

```

</details>

Questions:
* Should we address these cases?
* Should we enable this lint rule (or an improved version of it)?
* Can certain sims (not common code) opt out of this lint rule based on developer discretion?

I'm also looking forward to discussing @jonathanolson's remarks.  I think webpack should have a way of doing this, but I didn't see anything trivial/simple to accomplish it. And if webpack did have a way, it would be different than running in "unbuilt" mode.  I don't know if built vs unbuilt symmetry is important for maintenance releases.

**Comment by zepumph** [comment]
I think that a lint rule makes a ton of sense. I'll work on improving it a bit here.

**Comment by zepumph** [comment]
I am incredibly surprised and relieved at how easy it was to expand your draft to include cases where you have a class variable and then call `export default MyClass` later. I then fixed all usages and turned on the rule.

@samreid I know that you are not incredibly excited about this eagerly, but you can opt out for your repos (either in the lint rule file, or with our normal strategies in the package.json files.  

Will you please review and recommend?

**Comment by samreid** [comment]
Nice work @zepumph, that is a well-written ESLint rule.  My main questions are around opting out:

```ts
// Repos without a namespace that don't require these register calls.
const optOutRepos = [ 'aqua', 'phet-io-wrappers', 'quake', 'studio' ];
```

When I was tinkering with a class in perennial, I saw it wanted me to namespace it.  So I'm wondering if we should add to this list (maybe chipper as well?) Or if it would be more natural to turn off this rule in those repos package.json files.

**Comment by zepumph** [comment]
Sounds good to me! I think that a lack of namespaces for the aforementioned repos is inherent to the rule, and as a result I recommend it in the rule. I see sprinkling things out in package.jsons as more applicable when developer discretion is at play, or chip away that will take a long long time. 

That said it could be confusing for somewhere to find this list. Up to you!

**Comment by samreid** [comment]
> @samreid I know that you are not incredibly excited about this eagerly, but you can opt out for your repos (either in the lint rule file, or with our normal strategies in the package.json files.

I read through this issue and do not see any comments describing the value of namespace registrations in simulation code. Is there a practical value in that? If not, can we agree to make it developer preference for simulations (indicated in eslint overrides in package.json)?

**Comment by marlitas** [comment]
Dev Meeting 12/22/22

JG: I found it very helpful for debugging this past week.
CK: Can you describe that process more?
JG: If a sim is registered you can go to phet.{{SIM_NAME}} in dev tools and access the object through there.
CM: I've also found it useful to create examples without creating a full sim. 
JO: I've used it for sim code to test things out. However, the primary maintenance and benefit is in common code usage for me.
CK: I also don't use it in sims.
CM: What is the cost of keeping this? I use a live template and that does it automatically.
SR: I don't see how sim code usage for this is practical with complicated classes or constructors. I see it as clutter and not providing any value, so I would prefer to remove it.
JB: What about consistency between sims? I am open to either way, but there should be a policy: do it or don't. Should not be developer discretion.
MV: I agree with JB
SR: It sounds like we value consistency more, so we should keep it and move forward.

Ready to close.

**Comment by samreid** [comment]
I think everything in scope for this issue is complete. CT is clear. I added a lint rule to prevent developer templates from resurrecting unwanted register calls. We cannot remove Namespace since it is used for Color registration and similar things like that. There are some stale imports in string files, which are not too concerning.

**Comment by samreid** [comment]
Well, on second thought, I would like to check in with devs to make sure there are no other use cases I did not discover. For instance, during my work I saw many usages in "playground" and "documentation" files, and not sure how to know if I dealt with all cases. So I'll put on dev meeting agenda.

**Comment by samreid** [comment]
At last dev meeting, we agreed:

> We’re all good to go here.

That being said, running daily-grunt-work over in https://github.com/phetsims/totality/issues/35 triggered re-creation of the namespaces in image, sound, and fluent files. I think those are safe to omit, except maybe in certain repos like sun or scenery-phet. They aren't hurting anything. But I'll reopen to evaluate more closely.

**Comment by samreid** [comment]
Since playground and sandbox apps may use these from some repos, and since these are auto-generated, we (I) have decided they are ok and will not be removed as part of this issue, re-closing.
