### ISSUE TITLE
Subclassing an Enumeration more than once causes a bug

### ISSUE THREAD

**Issue by chrisklus** [phetsims/phet-core#101]
I'm experiencing a weird bug from the following Enumeration structure:

PlayObjectType is a base type with values DOG, APPLE, BUTTERFLY, and BALL.
CountingObjectType is a subclass of PlayObjectType that adds the value PAPER_NUMBER.
These two live in counting-common, but are also imported into number-play.

SubitizeObjectType is also a subclass of PlayObjectType that adds the value CIRCLE.
This is in number-play only.

In Number Play sim code, at runtime, CountingObjectType has the values that SubitizeObjectType does instead of the values it should have. If I remove SubitizeObjectType from this relationship, CountingObjectType has the correct values. I just now discovered this problem because this is the first time I've needed to use CountingObjectType in number-play code. It's been working fine in counting-common code. I don't think I'm doing anything with SubitizeObjectType on the number play side of things could be messing with CountingObjectType, and have tested that by removing almost all usages of SubitizeObjectType. It seems like if I define the Enumeration and never use it, the problem does not occur, but if I reference it just once, like for the instantiation of an EnumerationProperty, the problem does occur.

I will commit the change that'll allow the sim to run to this issue so it is easy to see how to reproduce the problem.  

@zepumph if you have any time tomorrow I would very much appreciate your help with this.

**Comment by zepumph** [comment]
Hello! Thanks for the bug report. I cannot seem to reproduce this though.

I put debugger statements after creation of the Enumeration subtypes, and see that their `enumeration` instance, and available static keys were all correct.

I then put a debugger at Subitzer:193 and checked both of them again on the namespace. Counting* has CIRCLE, and Subitizer* has PAPER_NUMBER. It wasn't clear to me if the above commit was supposed to error something, or where to look to demonstrate this issue. Can I get a bit more explanation? Or perhaps a pair if you'd prefer.

**Comment by zepumph** [comment]
Also, this has the blocking-sim label on it, but it is in common code. Please change to blocks-publication and or mention what sims are blocked by this bug.

**Comment by zepumph** [comment]
Looks like my transpiler hadn't caught up since your commit. I'll take another look.

**Comment by chrisklus** [comment]
I suppose my commit above makes this not blocking, since CountingObjectType can conveniently be reused in it's place (just the wrong name). Removing label.

Thanks for taking a look, let me know if you are still can't reproduce.

**Comment by zepumph** [comment]
Ok, even with the new commits, I can't seem to find the bug. It would probably be good to find some time to discuss this, and have you drive.

**Comment by zepumph** [comment]
Ignore the above comment, I didn't see https://github.com/phetsims/phet-core/issues/101#issuecomment-1029204885 come in.

**Comment by zepumph** [comment]
Ok. I have finally been able to reproduce the bug (I think).

1. Revert https://github.com/phetsims/number-play/commit/dfe4ab05f65cdef1cde0da25fad212e9c18350fc
2. Debugger on CompareModel:37
3. Open in dev tools and see that CountingObjectType has the right values, as it should, but leftCountingObjectTypeProperty.validValues is pointing to the SubitizeObjectType items (CIRCLE).


I'll take a look at what is going on in EnumerationProperty.

**Comment by zepumph** [comment]
We are getting the instance of the Enumeration from the value, which doesn't work well with subtypes:

https://github.com/phetsims/axon/blob/6219ae176f5fa0056aef625ff163dd7c5ffc4aa4/js/EnumerationProperty.ts#L28

Notice that the value is from the supertype, so the enumeration instance is different.

From this, I would recommend not supporting subtyping enumerations. It is too clever. Would it work to duplicate there, and perhaps just make an assertion in subtypes that all supertype keys are provided on construction?


```diff
Index: js/game/model/SubitizeObjectType.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/game/model/SubitizeObjectType.ts b/js/game/model/SubitizeObjectType.ts
--- a/js/game/model/SubitizeObjectType.ts	(revision 85fc259efe9e35a6a67eb374e129990864a757b8)
+++ b/js/game/model/SubitizeObjectType.ts	(date 1643910545061)
@@ -10,14 +10,24 @@
 import Enumeration from '../../../../phet-core/js/Enumeration.js';
 import numberPlay from '../../numberPlay.js';
 import PlayObjectType from '../../../../counting-common/js/common/model/PlayObjectType.js';
+import EnumerationValue from '../../../../phet-core/js/EnumerationValue.js';
 
-class SubitizeObjectType extends PlayObjectType {
+class SubitizeObjectType extends EnumerationValue {
+  static DOG = new SubitizeObjectType();
+  static APPLE = new SubitizeObjectType();
+  static BUTTERFLY = new SubitizeObjectType();
+  static BALL = new SubitizeObjectType();
   static CIRCLE = new SubitizeObjectType();
 
-  static enumeration = new Enumeration( SubitizeObjectType, {
-    instanceType: PlayObjectType
-  } );
+  static enumeration = new Enumeration( SubitizeObjectType );
 }
+
+// TODO: perhaps we can do this with typescript somehow? Is it worth it?
+assert && PlayObjectType.enumeration.keys.forEach( key => {
+
+  // @ts-ignore
+  assert && assert( SubitizeObjectType[ key ] instanceof SubitizeObjectType, `${key} must be part of SubitizeObjectType` );
+} );
 
 numberPlay.register( 'SubitizeObjectType', SubitizeObjectType );
 export default SubitizeObjectType;

**Comment by chrisklus** [comment]
From work that @zepumph did in https://github.com/phetsims/phet-core/issues/102, we still support subtyping enumerations, woohoo! Notes on using them in https://github.com/phetsims/phet-core/issues/102#issuecomment-1041874848. Closing.
