### ISSUE TITLE
Missing doc in optionize.ts

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-core#104]
optionize.ts is missing summary documentation at the top of the file, and `@author` annotation.

**Comment by samreid** [comment]
@zepumph how do you think we should document optionize.ts and WilderOptionsPatterns.ts?

**Comment by zepumph** [comment]
Hows that for now? One of the topics for https://github.com/phetsims/chipper/issues/1128 is to update the design patterns document, so I think of this as temporary.

**Comment by pixelzoom** [comment]
Doc looks good to me. Fixed one capitalization error in the above commit.  Closing.
