### ISSUE TITLE
`optionize` doesn't recognize when defaults are provided for required superclass options.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-core#106]
I'm wondering if `optionize`is working correctly in a specific use case.  My superclass has `provideOptions` that are all required.   My subclass provides values for those superclass options.  Here's an example:

```ts
// Copyright 2022, University of Colorado Boulder

import optionize from '../../../../phet-core/js/optionize.js';

type OpticOptions = {
  diameter: number,
  radiusOfCurvature: number
}

class Optic {

  readonly diameter: number;
  readonly radiusOfCurvature: number;

  constructor( providedOptions: OpticOptions ) {
    this.diameter = providedOptions.diameter;
    this.radiusOfCurvature = providedOptions.radiusOfCurvature;
  }
}

type LensSelfOptions = {
  indexOfRefraction: number
};

type LensOptions = LensSelfOptions;

class Lens extends Optic {
  constructor( providedOptions: LensOptions ) {

    const options = optionize<LensOptions, LensSelfOptions, OpticOptions>( {
      diameter: 10,
      radiusOfCurvature: 20
    }, providedOptions );

    super( options );
  }
}

export default Lens;
```

The call to `super( options )` gets flagged as a TypeScript error:

```
error TS2345: Argument of type 'Required<Options<LensSelfOptions>> & Partial<OpticOptions> & Required<Pick<OpticOptions, never>> & LensSelfOptions' is not assignable to parameter of type 'OpticOptions'.
  Types of property 'diameter' are incompatible.
    Type 'number | undefined' is not assignable to type 'number'.
      Type 'undefined' is not assignable to type 'number'.
```

I can only resolve the error by enumerating ALL of the superclass' required options as the 4th type variable to `optionize`:

```js
const options = optionize<LensOptions, LensSelfOptions, OpticOptions, 'diameter' | 'radiusOfCurvature'>( {
```

The 4th type variable to `optionize` is documented as:

```ts
// KeysUsedInSubclassConstructor = list of keys from ParentOptions that are used in this constructor
```

So I'm wondering...  Is this how `optionize` is supposed to work in this case? Is providing default values for required superclass options considered "used in this constructor"? (This is technically defining fields, not using them.)  Does `optionize` look at its `defaults` argument to see which keys are provided? Anything we can do to change this?  It sure is inconvenient to have to duplicate these option keys.

**Comment by pixelzoom** [comment]
P.S.  While the above example only has 2 required options in the constructor, my real cases have more options, and the duplication is consequently uglier, and more of a pain point to keep in-sync.  For example in Lens.ts:

```ts
    const options = optionize<LensOptions, SelfOptions, OpticOptions,
      'opticShapes' | 'diameterRange' | 'sign' | 'directFocalLengthModelOptions' | 'indirectFocalLengthModelOptions'>( {
      opticShapes: providedOptions.isBasicsVersion ? [ 'convex' ] : [ 'convex', 'concave' ],
      diameterRange: GOConstants.DIAMETER_RANGE, // in cm
      sign: 1,
      directFocalLengthModelOptions: {
        focalLengthMagnitudeRange: new RangeWithValue( 30, 130, 80 ), // in cm
        indexOfRefractionRange: new RangeWithValue( DIRECT_INDEX_OF_REFRACTION, DIRECT_INDEX_OF_REFRACTION, DIRECT_INDEX_OF_REFRACTION ), // fixed and unitless
        tandem: focalLengthModelsTandem.createTandem( 'directFocalLengthModel' )
      },
      indirectFocalLengthModelOptions: {
        radiusOfCurvatureMagnitudeRange: new RangeWithValue( 30, 130, 80 ), // in cm
        indexOfRefractionRange: new RangeWithValue( 1.2, 1.9, 1.5 ), // unitless
        tandem: focalLengthModelsTandem.createTandem( 'indirectFocalLengthModel' )
      }
    }, providedOptions );
```

**Comment by pixelzoom** [comment]
Would it be possible to harvest the keys from `defaults` and automatically add them to the `KeysUsedInSubclassConstructor` type variable?  So if you provided a value for a key in `default`, you wouldn't need to duplicate that key again in `KeysUsedInSubclassConstructor`.

**Comment by zepumph** [comment]
Yes, this sounds like "Limitation I":

https://github.com/phetsims/wilder/blob/5bb2fd7da11a72d30acac3e06548d7b65d1a8b4e/js/wilder/model/WilderOptionsPatterns.ts#L51-L52

Am I right about that? I think this is one of the top two items I would want to improve on optionize, but I don't know when I will get to it.

**Comment by pixelzoom** [comment]
Yes, you're correct:
> (I) Required parameters of parent options can potentially be specified by defaults in the subtype, or through providedOptions. The current optionize does not know where it comes from, and cannot guarantee that its return value has the required parameter.

**Comment by pixelzoom** [comment]
Yes, you're correct:
> (I) Required parameters of parent options can potentially be specified by defaults in the subtype, or through providedOptions. The current optionize does not know where it comes from, and cannot guarantee that its return value has the required parameter.

So...  I should live with the duplication for now, and we close this issue?

**Comment by zepumph** [comment]
Yes, I think so, just add a comment about how you have to get around Limitation (III) (defined in WilderOptionsPatterns).

Hopefully one day we will be able to fix this problem with optionize. It is documented as part of the work still to do in https://github.com/phetsims/chipper/issues/1128.

**Comment by pixelzoom** [comment]
> Yes, I think so, just add a comment about how you have to get around Limitation (III) (defined in WilderOptionsPatterns).

Why does this involve Limitation (III).  I thought I was working around Limitation (I)?

**Comment by pixelzoom** [comment]
> Yes, I think so, just add a comment about how you have to get around Limitation (III) (defined in WilderOptionsPatterns).

Why does this involve Limitation (III).  I thought I was working around Limitation (I)?

It sounds to me like we should add an example to WilderOptionsPatterns, showing how to workaround Limitation (I).  And that example could be something like https://github.com/phetsims/phet-core/issues/106#issue-1148970245. @zepumph do you agree?

**Comment by zepumph** [comment]
Oops, yes limitation (I), sorry, I was working with Limitation (III) in another case yesterday.

I agree about the example. I'll write it up. Thanks!

**Comment by zepumph** [comment]
How's that?

**Comment by zepumph** [comment]
Also please note https://github.com/phetsims/phet-core/blob/5404829dac3a4d0929db100ee6a7a5a8b948348b/js/optionize.ts#L46

**Comment by pixelzoom** [comment]
👍🏻
