### ISSUE TITLE
Rename Defaults to OptionizeDefaults.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-core#107]
In optionize.ts:

```ts
export type { Defaults };
```

This name is too general. Let's rename to `OptionizeDefaults`.

**Comment by zepumph** [comment]
How about `DefaultOptions`

**Comment by pixelzoom** [comment]
`DefaultOptions` is still too general imo. Defaults for what? `OptionizeDefaults` is only 3 chars longer..

The documentation for Defaults says that's it's the defaults for optionize:

```ts
// This is the type for the `defaults` argument to optionize
type Defaults<SelfOptions = ...
```

... so why not name it as such?

**Comment by pixelzoom** [comment]
Here's a typical example from geometric-optics (FocalLengthControl.ts) for context:

```js
// Assemble the defaults for NumberControl, because optionize doesn't currently support defaults in multiple objects.
const numberControlDefaults: Defaults<{}, NumberControlOptions> = merge( {}, ..., {
 ...
} );

const options = optionize<FocalLengthControlOptions, {}, NumberControlOptions>( {}, numberControlDefaults, providedOptions );
```

**Comment by zepumph** [comment]
I like OptionizeDefaults, thanks for talking it through with me. Please review.

**Comment by pixelzoom** [comment]
👍🏻 closing
