### ISSUE TITLE
Create ReqOpt type

### ISSUE THREAD

**Issue by samreid** [phetsims/phet-core#108]
From https://github.com/phetsims/phet-io/issues/1843

If we had `WithOptional` and `WithRequired`, combinations would be unwieldy:

```ts
type BuildANucleusModelOptions = BuildANucleusModelSelfOptions & WithRequired<WithOptional<PhetioObject, 'otherOption'>, 'tandem'>;
```

How about one type that can do both?

```ts
type ReqOpt<T, Required extends keyof T, Optional extends keyof T = never> = ...;

type PersonOptions = {
  name: string;
  height: number;
  address?: string;
  age?: number;
};

// Make address and age required, and change name to optional.  Keep everything else as it was.
type OtherPersonOptions = ReqOpt<PersonOptions, 'address' | 'age', 'name'>
```

The options 2nd arg could default to `never` so you could use it to promote to required things easily:

```ts
type PersonWithAddress = ReqOpt<PersonOptions, 'address'>
```

Demoting something to optional would be more awkward because of the `never`.

```ts
type PersonWithAddress = ReqOpt<PersonOptions, never, 'name'>
```

If we like this idea, it would be nice to have a better name.  `ReqOpt` is cryptic--I just wrote it as a placeholder to get the idea across.

**Comment by samreid** [comment]
I wrote up a variation on this proposal in https://github.com/phetsims/phet-info/issues/187#issuecomment-1059804244.  Let's discuss that first before working further on this issue.

**Comment by pixelzoom** [comment]
Sorry, I'm not a fan of the `SparseExtends` proposal. I see no clear pros, and several cons. See https://github.com/phetsims/phet-info/issues/187#issuecomment-1059807464.

**Comment by pixelzoom** [comment]
We've been using `PickRequired` and `PickOptional` for some time now.  @samreid can this issue be closed?

**Comment by samreid** [comment]
I think this issue can be closed, but I just wanted to mention that in https://github.com/phetsims/chipper/issues/1266 we are looking at upgrading our library for creating options--may have some overlap with this proposal.  I'll comment there and close this.
