### ISSUE TITLE
Should PickRequired and PickOptional have a default export?

### ISSUE THREAD

**Issue by samreid** [phetsims/phet-core#112]
While reviewing https://github.com/phetsims/phet-io/issues/1543, I was surprised see that this didn't work:

```ts
import PickOptional from '../../phet-core/js/types/PickOptional.js';
```

Instead, I see examples like:

```ts
import { PickRequired } from '../../../../phet-core/js/types/PickRequired.js';
import { PickOptional } from '../../../../phet-core/js/types/PickOptional.js';
```

Is this by intention?  Is this a new precedent?

**Comment by pixelzoom** [comment]
types cannot be default exports, is my understanding, because they are removed by tsc.  And any non-default import will be surrounded by `{ … }`.

**Comment by pixelzoom** [comment]
In Slack, @samreid established that this works:

```
type PickOptional<T, list extends keyof T> = Pick<Partial<T>, list>;
export default PickOptional;
```

This does not work, so is an exception to our ability to "export where defined", as was recently added to TypeScript code conventions.

```
export default type PickOptional<T, list extends keyof T> = Pick<Partial<T>, list>;
```

**Comment by pixelzoom** [comment]
> Is this by intention? Is this a new precedent?

This is a holdover from the `export` convention that originally appeared in typescript-conventions.md, which said that types were NOT to be a default export:

> When exporting multiple modules, all types should be combined into 1 `export` statement, and all non-types should be
combined into 1 `export` statement. So a .ts file should have at most 2 `export` statements. For example:
> 
```ts
type DogOptions = ...;
type CollarOptions = ...;

class Dog { ... }
class Collar { ... }

export { DogOptions, CatOptions }; 
export { Dog as default, Collar };
```

**Comment by samreid** [comment]
Yes, but that convention does not apply since we are not exporting multiple modules.  8 out of the 10 types declared in phet-core/types are using `export default` for a type.  2 are not.  We should choose which we prefer and be consistent.

**Comment by pixelzoom** [comment]
I was not justify the pattern, I was explaining why it's not currently a default export.

5 minutes to change export to default + 10 minutes to investigate failing axon unit tests that prevented committing + 15 minutes to fix my working copy that got totally messed up when commits failed + 5 minutes to visit each affected repo and manually push. 

PickRequired and PickOptional are now default exports. Ready for review, close if OK.

**Comment by samreid** [comment]
My precommit hooks are showing problems with puppeteer, that may explain how the Emitter unit test failures got through:

```
~/apache-document-root/main/axon$ pch
Linting passed with results.length: 55
tsc passed
[Error: Failed to launch the browser process! spawn /usr/bin/chromium-browser ENOENT


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

  at onClose (/Users/samreid/apache-document-root/main/perennial/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
  at ChildProcess.<anonymous> (/Users/samreid/apache-document-root/main/perennial/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:185:85)
  at ChildProcess.emit (node:events:390:28)
  at Process.ChildProcess._handle.onexit (node:internal/child_process:288:12)
  at onErrorNT (node:internal/child_process:477:16)
  at processTicksAndRejections (node:internal/process/task_queues:83:21)
]

```

**Comment by samreid** [comment]
I reviewed the commits and everything looks great.  I opened a side issue about my failing precommit hooks.
