### ISSUE TITLE
How any required parameters does `optionize` have?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-core#120]
Here's an error that I make a few times a day. I've forgotten the second argument (`providedOptions`) to `optionize`:

```typeScript
export default class BeamNode extends Rectangle {

  public constructor( providedOptions: BeamNodeOptions ) {

    const options = optionize<BeamNodeOptions, SelfOptions, RectangleOptions>()( {

      // SelfOptions
      beamSize: new Dimension2( 30, 65 )
    } );
```

This feels buggy, so I'll label it as such -- but I'm not sure. Is there a use-case for calling `optionize` with a single argument? If not, it would be nice if type-checking could catch this error.

**Comment by pixelzoom** [comment]
`optionize3` apparently has a similar problem.  Only 2 arguments in this example, and no TS error:

```typescript
    const options = optionize3<RealLightRaysForegroundNodeOptions, SelfOptions, RealLightRaysNodeOptions>()( {}, {
        stroke: ( GOQueryParameters.debugRays ) ? 'red' : providedOptions.stroke
      } );
```

**Comment by pixelzoom** [comment]
And shouldn't `combineOptions` require at least 2 arguments? Otherwise there's no combining happening.  This example results in no TS error:

```typescript
 const arrowNodeOptions = combineOptions<ArrowNodeOptions>( GOConstants.ARROW_NODE_OPTIONS )
```

**Comment by zepumph** [comment]
The reason I didn't is this case:

```js
func( providedOptions? MyOptions ){
  const options = combineOptions<MyOptions>( { hi: true }, providedOptions );
}
```

In this case, since providedOptions could be undefined, it is problematic to not support just a single arg.

**Comment by pixelzoom** [comment]
Ah, right.  I don't see a way around that. So closing.
