### ISSUE TITLE
When is it type-safe and appropriate to use the spread operator for combining options?

### ISSUE THREAD

**Issue by samreid** [phetsims/phet-core#131]
In https://github.com/phetsims/axon/issues/437#issuecomment-1548810650 it said:

> (4) Destructuring should not be used in place of `combineOptions`, it is not type-safe.  For example, this passes a bad option to `new Emitter` and results in no tsc errors:
> 
```ts
  const junk = { foobar: true };
  const elementAddedEmitter = new Emitter<[ T ]>( {
    tandem: options.tandem.createTandem( 'elementAddedEmitter' ),
    parameters: [ emitterParameterOptions ],
    phetioReadOnly: true,
    hasListenerOrderDependencies: options.hasListenerOrderDependencies,
    ...options.elementAddedEmitterOptions,
    ...junk
  } );
```

There are a few problems with this.

* First, clarifying terminology for this conversation.  "Destructuring" refers to taking elements out of an object like `let { a, b, c } = obj;` The spread operator is [described like so](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax):

> The spread (...) syntax allows an iterable, such as an array or string, to be expanded in places where zero or more arguments (for function calls) or elements (for array literals) are expected. 

* Second, the example above is type safe. It passes type checking and does not have a type error. However, it does suffer from a related problem which is that it does not perform excess property checking on the elements of `junk`. I agree we should perform excess property checking in cases like this and I was happy to accept the `combineOptions` patch in https://github.com/phetsims/axon/issues/437#issuecomment-1548810650.  However, this does not mean that when the spread operator is used in an options combination that there will be no excess property checking.  For example: `foo:'bar'` in the object literal is detected as an excess property:

![image](https://github.com/phetsims/phet-core/assets/679486/b6419db2-f2f2-4da5-b89e-3e2cc27b230a)

We are using the spread operator in the development of Center and Variability, for instance, see https://github.com/phetsims/center-and-variability/blob/0fc7638eaffe3ef310897fe4668408e1e7a0f3f4/js/mean-and-median/view/MeanAndMedianPlotNode.ts#L29-L33

```ts
  public constructor( model: MeanAndMedianModel, sceneModel: CAVSceneModel, providedOptions: MeanAndMedianPlotNodeOptions ) {
    super( model, sceneModel, {
      dataPointFill: 'black',
      ...providedOptions
    } );
```

I do not feel that code has a type error or any problems with excess property checking.  No excess properties can leak in through the object literal, and no excess properties can leak in through the providedOptions, since they are already typed as `MeanAndMedianPlotNodeOptions`.  The main risk would be if someone one day sneaks in another spread object into that expression. But if that happens, it will not fail the type checker unless it has a conflict.

I would also note that TypeScript introduced `satisfies` in 4.9 which could be used to detect excess properties in spread objects:

![image](https://github.com/phetsims/phet-core/assets/679486/92f47b4a-a1bb-47b5-8bed-78da3d4a424b)

But that doesn't seem superior to `combineOptions`, mainly because you could forget to use it.

My main question is whether we can continue to use the spread operator to combine options in CAV or if it must be converted to `combineOptions`.  @pixelzoom @marlitas @matthew-blackman what do you recommend?

**Comment by pixelzoom** [comment]
Yes, sorry... spead operator, not destructuring. Point taken.

Imo using the spread operator instead of combineOptions is lazy programming.  If that's what you want to do (and promote) and other devs don't have a problem with it, then go for it.

**Comment by pixelzoom** [comment]
```ts
  const junk = { foobar: true };
  const elementAddedEmitter = new Emitter<[ T ]>( {
    tandem: options.tandem.createTandem( 'elementAddedEmitter' ),
    parameters: [ emitterParameterOptions ],
    phetioReadOnly: true,
    hasListenerOrderDependencies: options.hasListenerOrderDependencies,
    ...options.elementAddedEmitterOptions,
    ...junk
  } );
```

> Second, the example above is type safe. ...

Please explain how this example is typesafe.  It is passing excess properties to `new Emitter`, with no tsc errors.  How its that typesafe?

To clarify... Using the spread operator for options can be typesafe.  But you need to take extra measure to make it so., and it is possible (as in the above example) to do something that is not typesafe.  So why not uniformly use combineOptions, and avoid the pitfalls of using the spread operator?

**Comment by pixelzoom** [comment]
It's disturbing that I see this pattern (anti-pattern?) used throughout CAV.

**Comment by samreid** [comment]
> Imo using the spread operator instead of combineOptions is lazy programming.

Thanks, the reason I raised this issue is to try to understand the reasoning behind this sentiment.

> The other point here is that we agreed (as a team) on using specific patterns for "options". We (and I) spent a lot of time developing and documenting those patterns.

At the time we developed `combineOptions`, we were not aware that the spread operator was a viable alternative.  After discovering it and testing it, I feel it is preferable, and if there are no objections we could delete `combineOptions` altogether.

> Please explain how your statement here is true. This example is passing excess properties to new Emitter, with no tsc errors. How its that typesafe?

Thanks for changing my mind! I agree it is not type safe to miss those excess properties.

So if we change the team consensus and documentation, would it be OK to use the spread operator in cases like MeanAndMedianPlotNode.ts described above?  Or still lazy?

Two more points about excess property checking:
* First, excess properties are not checked in this code where I added a junk object to the `optionize` in `GuidesNode`.  Is that a problem:
```ts
export default class GuidesNode extends Node {

  public constructor( guides: Guides, armColor: TColor,
                      modelViewTransform: ModelViewTransform2, providedOptions: GuidesNodeOptions ) {

    const junk = { foo: 'bar' };
    super( optionize<GuidesNodeOptions, SelfOptions, NodeOptions>()( {

      // NodeOptions
      children: [
        new GuideNode( guides.topGuide, armColor, modelViewTransform ),
        new GuideNode( guides.bottomGuide, armColor, modelViewTransform )
      ],
      ...junk
    }, providedOptions ) );
  }
}
```

* Second, part I'm confused about and would like to understand better is excess properties get through a lot of places in our code.  For instance, if you pause the debugger in Node.ts, the options have a lot more things than just the node options.  I'm not seeing where this disconnect is happening.

**Comment by pixelzoom** [comment]
It is most certainly a related problem.  Again:
> To clarify... Using the spread operator for options can be typesafe, but does not guarantee type safety like optionize /combineOptions do. One needs to take extra measures to ensure type safety, be aware of the potential problems, and it is possible (as in the above example) to do something that is not typesafe. So why not uniformly use optionize/combineOptions, and avoid the pitfalls of using the spread operator?

There are pitfalls to using spread for options.  One must understanfd those pitfalls.  CAV demonstrates that you do not understand the pitfalls.   And why do this at all when optionize/combineOptions avoid the pitfalls?

**Comment by samreid** [comment]
Your patch actually changed the parameter type, not an argument.  Happy to discuss on zoom.

**Comment by pixelzoom** [comment]
Here's another example:

```diff
Subject: [PATCH] convert to TypeScript
---
Index: js/common/view/CAVScreenView.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/CAVScreenView.ts b/js/common/view/CAVScreenView.ts
--- a/js/common/view/CAVScreenView.ts	(revision ccfef71c8827dc74958b20817614a36cf1e15946)
+++ b/js/common/view/CAVScreenView.ts	(date 1684420037348)
@@ -13,7 +13,7 @@
 import CAVConstants from '../CAVConstants.js';
 import ResetAllButton from '../../../../scenery-phet/js/buttons/ResetAllButton.js';
 import ModelViewTransform2 from '../../../../phetcommon/js/view/ModelViewTransform2.js';
-import { AlignBox, Node } from '../../../../scenery/js/imports.js';
+import { AlignBox, Node, TextOptions } from '../../../../scenery/js/imports.js';
 import EraserButton from '../../../../scenery-phet/js/buttons/EraserButton.js';
 import QuestionBar, { QuestionBarOptions } from '../../../../scenery-phet/js/QuestionBar.js';
 import NumberLineNode from './NumberLineNode.js';
@@ -40,6 +40,7 @@
 
 type SelfOptions = {
   questionBarOptions: QuestionBarOptions;
+  textOptions?: TextOptions; // we intend to pass these to a Text subcomponent
 };
 
 export type CAVScreenViewOptions = SelfOptions & ScreenViewOptions;
@@ -72,7 +73,9 @@
   private readonly updateMedianNode: () => void;
 
   public constructor( model: CAVModel, providedOptions: CAVScreenViewOptions ) {
-    const options = optionize<CAVScreenViewOptions, SelfOptions, ScreenViewOptions>()( {}, providedOptions );
+    const options = optionize<CAVScreenViewOptions, SelfOptions, ScreenViewOptions>()( {
+      textOptions: {}
+    }, providedOptions );
 
     // View size of a soccer ball
     const objectHeight = 41;
@@ -167,6 +170,7 @@
 
     this.questionBar = new QuestionBar( this.layoutBounds, this.visibleBoundsProperty, {
       ...options.questionBarOptions,
+      ...options.textOptions,
       tandem: options.tandem.createTandem( 'questionBar' )
     } );
     this.contentLayer.addChild( this.questionBar );
```

I assed `textOptions` with the intention of passing it to a Text subcomponent.  I'm accidentally passing it to QuestionBar.  Again, no TSC error.   Is this also unrelated?

**Comment by samreid** [comment]
In discussion with @pixelzoom, we discovered there were masked type errors in Center and Variability. I'll commit one example of that in a moment. We would like to try converting Center and Variability towards mostly `optionize` and perhaps a few `combineOptions` and see how it goes.

**Comment by samreid** [comment]
OK I committed an example of a type error that was being masked by the spread operator in https://github.com/phetsims/center-and-variability/commit/f36330bca5cadf117a36f2611819fb8f80b4e3cb.  I'll continue in https://github.com/phetsims/center-and-variability/issues/214 and bring questions back here if there are any.  @pixelzoom want to close this issue or eagerly search around other repos or common code for other places that should be converted?

**Comment by samreid** [comment]
UPDATE: Or we could search for/build a lint rule to detect suspicious cases.  Maybe something like "only object literals are allowed when using the spread operator on objects"?

**Comment by pixelzoom** [comment]
Start by searching for "...options" -- you'll find cases in other repos.

**Comment by samreid** [comment]
I committed a rule (currently off) that can be used to prohibit the object spread operator in object expressions (arrays ok though).

**Comment by samreid** [comment]
I enabled the rule for CAV though and it helped me catch all cases.

**Comment by samreid** [comment]
After discussing this issue, I feel I have a better answer to the question "When is it type-safe and appropriate to use the spread operator for combining options?"

Using the spread operator on an object (not array and not an object literal) disables excess property checking which is undesirable. This applies in any circumstances, including but not limited to options and combining options.  We added a lint rule which can prohibit the spread operator for non-array, non-literals used in an object context.

**Comment by pixelzoom** [comment]
@samreid ready to close?

**Comment by samreid** [comment]
I wrote up a PSA for next dev meeting.  Closing.

**Comment by samreid** [comment]
Some quick notes before next discussion:

* The main consideration here is that we want to leverage excess property checking, but that only works on object literals, so we should prefer object literals where possible.

For instance:

```ts
type Person = {
  age?: number;
  name: string;
};

const p: Person = {
  name: 'John',
  agee: 42 // Hooray, it caught a typo
};

const otherThing = {
  name: 'John',
  agee: 42
};

const p2: Person = otherThing; // Missed opportunity, did not catch my typo
```
This is not specific to the spread operator or optionize.  For instance, if you make this change:

```diff

Subject: [PATCH] Use combineOptions, see https://github.com/phetsims/phet-core/issues/131
---
Index: js/common/model/SoccerBall.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/model/SoccerBall.ts b/js/common/model/SoccerBall.ts
--- a/js/common/model/SoccerBall.ts	(revision c8b518da717305e724a53c706ecb383918b4d3fe)
+++ b/js/common/model/SoccerBall.ts	(date 1685108170001)
@@ -72,9 +72,10 @@
 
   public constructor( public readonly isFirstSoccerBall: boolean, providedOptions: SoccerBallOptions ) {
 
-    const options = optionize<SoccerBallOptions, SelfOptions, PhetioObjectOptions>()( {
-      phetioState: false
-    }, providedOptions );
+    const myDefaults = {
+      pheti0State: false
+    };
+    const options = optionize<SoccerBallOptions, SelfOptions, PhetioObjectOptions>()( myDefaults, providedOptions );
     super( options );
 
     this.positionProperty = new Vector2Property( new Vector2( 0, CAVObjectType.SOCCER_BALL.radius ), {

```

then it will no longer catch that typo.

**Comment by samreid** [comment]
I'm not too worried about this issue.  I feel that the case in circuit construction kit may be appropriate:

```ts
    toStateObject: ( resistor: Resistor ): ResistorState => {
      const stateObject = CircuitElement.CircuitElementIO.toStateObject( resistor );
      return {
        ...stateObject,
        resistorType: EnumerationIO( ResistorType ).toStateObject( resistor.resistorType )
      };
    },
```

I feel it is more about using object literals where possible and knowing that variables and varargs disable excess property checking.  I didn't feel confident committing on too many various repos listed above.  @pixelzoom or @zepumph how do you want to proceed?

**Comment by pixelzoom** [comment]
I look at the example in https://github.com/phetsims/phet-core/issues/131#issuecomment-1581795111, and ask "why?" Why did the programmer go to the trouble of defining ResistorState (improperly btw, accordiong to PhET's options pattern) and CircuitElementState? And then use an entirely different pattern in `toStateObject` to combine the options?

Why not define the types properly, and use them where you can?  I.e.:

```ts
type ResistorStateSelfOptions = {
  resistorType: ResistorType;
};
type ResistorState = ResistorStateSelfOptions & CircuitElementState;

    toStateObject: ( resistor: Resistor ): ResistorState => {
      const stateObject = CircuitElement.CircuitElementIO.toStateObject( resistor );
      return optionize< ResistorState , ResistorStateSelfOptions , CircuitElementState >()( {
        resistorType: EnumerationIO( ResistorType ).toStateObject( resistor.resistorType )
      } );
    },
```

**Comment by zepumph** [comment]
`optionize` is absolutely not for anything other than the PhET options pattern. There are large assumptions about how you specify each parameter to the function, and how TypeScript should behave. Please do not use `optionize` anywhere else. If you want another, optionize-like function for cases like this, and `combineOptions` won't work for some reason, let me know and we can work on something. 

Mostly like the best path forward here is a synchronous discussion, because it isn't really even clear to me that we are all agreed in how important future work on this issue is, or if we should even have the lint rule at all.

**Comment by pixelzoom** [comment]
> `optionize` is absolutely not for anything other than the PhET options pattern. here are large assumptions about how you specify each parameter to the function, and how TypeScript should behave. Please do not use `optionize` anywhere else. ...

I'm not clear on why this in not an appropriate use of the options pattern. We're assembling an object literal that consists of a set of fields.  In general those fields may be optional or required.  A state object is a special case where they are all required.   If you're saying that the options pattern only applies to the `providedOptions` parameter for constructors/methods.... What specific "assumptions" are you referring to that prevent its use in other cases?

**Comment by zepumph** [comment]
`optionize` makes assumptions about what parameter (based on position) should have include and what behavior it should have. Also, the underlying runtime function, `PHET_CORE/merge`, is specifically implemented with phet's option pattern in mind (only expanding recursively to items ending in `Options`. Especially as a maintainer of one of the most complicated files in the code base (optionize), I would really rather not expand its usage beyond the options pattern. It already needs work and doesn't cover all cases well (like nested options).

@samreid and I found a nice way to use `_.merge` to accomplish the stateObject pattern. We also fixed all other problems, and committed the rule being turned on. I wanted to push on this and do it eagerly, since the majority of these cases were being lazy about options. We can still work on the best pattern for toStateObject composition if you'd like @pixelzoom.

**Comment by samreid** [comment]
@zepumph nice work and thanks! I reviewed and these seem like good changes.  I'll also add more about excess property checking to the typescript conventions doc.

**Comment by samreid** [comment]
I added a section on Excess Property Checking to the typescript doc, which is referenced from the code review guidelines.  I feel this issue is ready to close.  Should we check in with @pixelzoom or any sort of PSA?

**Comment by zepumph** [comment]
I posted to slack about the new lint rule, let's hear back from @pixelzoom, especially about https://github.com/phetsims/circuit-construction-kit-common/commit/ac7789949cfe94d5b254c8961e69d501837ab3b7. I think we are close to a close though.

**Comment by pixelzoom** [comment]
Thanks for elaborating in https://github.com/phetsims/phet-core/issues/131#issuecomment-1590222494.  I had forgotten about the constraints on nested options (the requirement for 'Options' suffix).   I can't say that I've had any need for nested options in StateObjects, but I get your point.   If `_.merge` is the path forward and provided type-safety, great -- let's document it in https://github.com/phetsims/phet-io/blob/master/doc/phet-io-instrumentation-technical-guide.md#io-types.

**Comment by zepumph** [comment]
Thanks!
