### ISSUE TITLE
Should PoolableMixin be lowercase and/or have a different name?

### ISSUE THREAD

**Issue by samreid** [phetsims/phet-core#16]
PoolableMixin is a function, but not a constructor function to be used with new.  Hence wherever it is used, a jshint directive must be given to suppress a warning for it.  For example, in SVGBlock:

```js
  /* jshint -W064 */
  PoolableMixin( SVGBlock, {
    constructorDuplicateFactory: function( pool ) {
      return function( display, renderer, transformRootInstance, filterRootInstance ) {
        if ( pool.length ) {
          sceneryLog && sceneryLog.SVGBlock && sceneryLog.SVGBlock( 'new from pool' );
          return pool.pop().initialize( display, renderer, transformRootInstance, filterRootInstance );
        }
        else {
          sceneryLog && sceneryLog.SVGBlock && sceneryLog.SVGBlock( 'new from constructor' );
          return new SVGBlock( display, renderer, transformRootInstance, filterRootInstance );
        }
      };
    }
  } );
```

Discovered during:
https://github.com/phetsims/scenery/issues/366

Our standard convention is that files should be named as they would be used in code, so if this is just a function, perhaps it should be poolableMixin, or addPoolingSupport or addPoolableMixin or mixinPoolable.  Thoughts @jonathanolson?

**Comment by jonathanolson** [comment]
Mixins describe a type/interface, like our other types do, however usually without an explicit constructor. Most languages generally capitalize mixins/traits the same way as classes/types, and for JS there are a number of references that capitalize it as I do (http://bob.yexley.net/dry-javascript-with-mixins/, http://addyosmani.com/resources/essentialjsdesignpatterns/book/#mixinpatternjavascript, http://facebook.github.io/react/docs/reusable-components.html, etc.). Additionally, some of the conventions mirror my own preferences to call it "Poolable", while one does use the suffix "Mixin" like our current PoolableMixin.

I've also seen "hasPoolable" or "asPoolable" as function conventions.

The act of doing the mixing (changing the prototype) sounds like the best candidate for lower case. My best proposal that will satisfy JSHint and myself would be:
```js
Poolable.mixin( SVGBlock, { ... options ... } );
```

Thus I'd advocate a change back to Poolable.js, but make the fact that it's mixing in things into the type explicit (and solves the same documentation issue that lead us to change Poolable => PoolableMixin).

**Comment by pixelzoom** [comment]
Sounds like a compromise we can live with. I also like the fact that it make the "mixing in" explicit.

**Comment by samreid** [comment]
Sounds great, thanks!

**Comment by jonathanolson** [comment]
Made the proposed mixin changes, reassigning in case you want to review.

**Comment by samreid** [comment]
I just took a quick look at Poolable.js and some mixin sites, everything seemed good. Closing.
