### ISSUE TITLE
Rename 'core' namespaces to 'phetCore'

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/phet-core#18]

**Comment by pixelzoom** [comment]
There may be other sites, but here are the ones that I identified:

(1) Rename phet-core/js/core.js to phetCore.js

(2) Throughout phet-core .js files, change `var core = require( 'PHET_CORE/core' );` to `var phetCore = require( 'PHET_CORE/phetCore' );`

(3) Rename phet-core/tests/qunit/js/core-tests.js to phetCore-tests.js

(4) In core-tests.js, change `module( 'Phet-core' )` to `module( 'phetCore')`.

(5) In scenery/tests/qunit/pixel-comparison.js, change `core` to `phetCore`

(6) In mobius/tests/triangle-css.js, change `core` to `phetCore`

**Comment by jonathanolson** [comment]
I'll take care of this issue now.

**Comment by jonathanolson** [comment]
Should be complete, please review or close.

**Comment by pixelzoom** [comment]
Looks like you skipped this one, any reason?

> (4) In core-tests.js, change module( 'Phet-core' ) to module( 'phetCore').

**Comment by pixelzoom** [comment]
@jonathanolson Looks like you skipped this one, any reason?

> (4) In core-tests.js, change module( 'Phet-core' ) to module( 'phetCore').

**Comment by jonathanolson** [comment]
Ahh, it's been convention there to have the string repo name, but capitalized. Since there are no restrictions about dashes, I had it included. So for example, it's module( "Scenery: Color" ), not module( "scenery: Color" ).

I don't have a strong preference, but I'd like to make it consistent.

**Comment by pixelzoom** [comment]
@jonathanolson wrote:
> it's been convention there to have the string repo name, but capitalized

Ah yes, I see that elsewhere in your code, like in dot/tests/qunit/js/bounds2:
> module( 'Dot: Bounds2' );

I'm curious about the "convention" aspect. Is this a qunit convention, or a @jonathanolson convention? Up to this point I've seen repos referred to either by their name (dot) or config.js path (DOT).  This adds a third name.  Seems like `module( 'dot.Bounds2' )` would be more aligned with how we refer to things elsewhere (github issues, Skype, doc, ...)

**Comment by jonathanolson** [comment]
I'm not sure of the qunit convention, I guess it's mine. On unit test pages, documentation, etc. I generally call it "Scenery" not "scenery", so that was carrying over.

I'm not against lower-case naming here, but just want to note that it's just the title of the test block that is named, and it's more general like:
```js
module( 'Scenery: Fuzzer Excerpts' );
```
or
```js
module( 'Scenery: Pixel Comparison' );
```
which show up as:
![scenery-unit-tests](https://cloud.githubusercontent.com/assets/480878/6837098/2e819426-d30e-11e4-9a73-f4dd68da5d5e.png)

**Comment by pixelzoom** [comment]
Let's just leave it "as is" for now, discuss it again (or not) if/when we get serious about quit test coverage for more repos.

Closing.
