### ISSUE TITLE
Delete profiler.js

### ISSUE THREAD

**Issue by samreid** [phetsims/phet-core#19]
AFAK it is unused.  Can we delete it @jbphet @pixelzoom @jonathanolson ?

**Comment by samreid** [comment]
Also the entry from main.js should be removed.

**Comment by pixelzoom** [comment]
I'm not using it.

**Comment by jonathanolson** [comment]
I'm not using it.

**Comment by pixelzoom** [comment]
If @jbphet is not using this, then I'll handle deleting it.

**Comment by pixelzoom** [comment]
Assigning to @jbphet to weigh in.

**Comment by jbphet** [comment]
I'm not using it.
