### ISSUE TITLE
add visibility annotations

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-core#21]
Add a @public, @protected or @private annotation to anything that's publicly visible.
See https://github.com/phetsims/tasks/issues/307.

**Comment by pixelzoom** [comment]
Currently, the only files that need annotations are EventTimer.js and (maybe) Poolable.js.

**Comment by jonathanolson** [comment]
Added annotations to EventTimer.js and Poolable.js. Anything else remaining?
