### ISSUE TITLE
Investigate ES6 inheritance, modules, etc.

### ISSUE THREAD

**Issue by samreid** [phetsims/phet-core#23]
From Tuesday, November 3 Developer Meeting notes, we decided to look into the ES6 features with an eye to how it relates to our current strategies and migration path.  In particular, modules and inheritance should be looked at, so that we can understand differences between our strategy and the ES6 strategy.  Will we get to a point where we are using both?  Update all our old code to use ES6 only?  Medium priority.

**Comment by pixelzoom** [comment]
We need to understand both differences and *compatibility* with our current strategies.

**Comment by pixelzoom** [comment]
Since we've been using ES6 for a few months now, it seems like this issue could be closed. @samreid please close if you agree.

**Comment by samreid** [comment]
To clarify, we are using ES6 `class extends` but not modules, and it seems to be working nicely, closing.
