### ISSUE TITLE
Should inherit be global?

### ISSUE THREAD

**Issue by samreid** [phetsims/phet-core#25]
From https://github.com/phetsims/sherpa/issues/65

@pixelzoom said:

> I'm not excited about having to add this `require` statement to almost every source file:
> 
> `var extend = require( 'PHET_CORE/extend' )`

@jonathanolson replied:

> Is it worth revisiting things like PHET_CORE/inherit to see if we should have globals for that?

**Comment by samreid** [comment]
> Is it worth revisiting things like PHET_CORE/inherit to see if we should have globals for that?

Yes, good point.  It seems odd to have a different pattern for doing inherit vs extend.

**Comment by samreid** [comment]
Consensus: it is easy to keep requiring it. We all have it in our templates, etc.  We'd rather not refer to it as `phet.phetCore.inherit`.

**Comment by pixelzoom** [comment]
@samreid Looks like we have a consensus, can this be closed?

**Comment by samreid** [comment]
Yes, the current pattern is clear and working well, and `phet.phetCore.inherit` looks pretty clumsy.  Closing.
