### ISSUE TITLE
Add safari 10  and 11 to platform.js

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/phet-core#31]
platform.js only checks up to safari9, for https://github.com/phetsims/resistance-in-a-wire/issues/112 I need to check for safari 10 and 11 too.

**Comment by jessegreenberg** [comment]
@samreid would you mind reviewing this as part of #32?

**Comment by jessegreenberg** [comment]
@jonathanolson volunteered to review #32, assigning to him for this issue as well.

**Comment by jonathanolson** [comment]
Looks good to me. (Edge/Chrome both have the "Safari" and "AppleWebKit" parts, but not the Version part, and hopefully it stays that way).
