### ISSUE TITLE
Add check for any version of safari to platform.js

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/phet-core#32]
In https://github.com/phetsims/resistance-in-a-wire/issues/112 I need to detect any version of safari, so I have something like 

```js
return ( platform.mobileSafari || platform.safari5 || platform.safari6 || platform.safari7 || platform.safari9 || platform.safari10 || platform.safari11 );
```

Can this general check be added to platform.js?

**Comment by jessegreenberg** [comment]
Maybe refactor check for mobile safari and add something like 
```
safari: isMobileSafari() || ( ua.match( /Safari\// ) && ua.match( /AppleWebKit/ ) ),
```

**Comment by jessegreenberg** [comment]
Ah, I see we need to check for 'Version', the above matches in chrome.

**Comment by jessegreenberg** [comment]
Added in the above commit.

**Comment by jessegreenberg** [comment]
@samreid, since you are the original author would you mind reviewing?

I tested that platform.safari is `true` for Safari 10.0.1, Safari on iOS 9.3.5, and `false` for Chrome and Firefox in macOS 10.12.1 and IE11, Edge, Firefox and Chrome in Windows 10.

**Comment by jessegreenberg** [comment]
@jonathanolson volunteered to review (Thanks!) assigning to him.

**Comment by jonathanolson** [comment]
Looks good to me, thanks!
