### ISSUE TITLE
ES6 permits improved options pattern

### ISSUE THREAD

**Issue by samreid** [phetsims/phet-core#34]
@jonathanolson pointed out

> If we transpile or can use ES6 features, there is an improved pattern for options.

```js
var options = { a: 5 };
var { a = 3, b = 10 } = options;
[ a, b ] // [ 5, 10 ]
```

**Comment by samreid** [comment]
Can you specify the advantages?  I’ll guess, but I want to hear your take on it.  What I’m seeing is: (a) no need for lodash, (b) less opportunity to forget the order of arguments to _.extend and (c) no need to use `options.` in front of option parameters.  Cons: if there are other variables in scope that clash with the option names, it could cause trouble.  Not clear how it impacts memory--may be a big win all of these vars are on the stack and there is no garbage generated.

**Comment by samreid** [comment]
If we use a transpiler, there is a good chance it will generate garbage for this step.  Hang on, I'll go check...

**Comment by samreid** [comment]
https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=G4QwTgBA9gDgLgSygOwM4QLwQN4RALggFYIBfAbgChRJcRMIBmAGggCMGBGABjIdkQpUVANp5WHALoQA9DIhiirHhElA&debug=false&circleciRepo=&evaluate=false&lineWrap=true&presets=es2015%2Creact%2Cstage-2&targets=&version=6.26.0

Transpiles https://github.com/phetsims/phet-core/issues/34#issue-276079625 to:

```js
"use strict";

var options = { a: 5 };
var _options$a = options.a,
    a = _options$a === undefined ? 3 : _options$a,
    _options$b = options.b,
    b = _options$b === undefined ? 10 : _options$b;

[a, b]; // [ 5, 10 ]
```

I'm not seeing any garbage, which is nice.

**Comment by samreid** [comment]
One of the reasons I wanted to stay on ES5 is so that no compilation step was necessary to test in the browser.  But now many browsers support ES6 out of the box--we could develop in ES6, test directly in ES6 without a compilation step, then transpile for publication (to support older browsers).

@jonathanolson what do you think?

**Comment by jonathanolson** [comment]
> we could develop in ES6, test directly in ES6 without a compilation step, then transpile for publication (to support older browsers).

I've been considering this, but was expecting others to reject the idea. Might be worth checking opinions now (or later, after people have used some of the features).

> Can you specify the advantages? I’ll guess, but I want to hear your take on it.

You guessed most of it. I also saw the "putting the names into local scope" as helpful, so we don't have to prefix every usage with `options.`.

**Comment by samreid** [comment]
Let's chat at next developer meeting.

**Comment by samreid** [comment]
I decided to move my notes about using ES6 in sim code to https://github.com/phetsims/chipper/issues/551 and this issue can remain focused on options pattern.

**Comment by samreid** [comment]
MDN has an example of using destructuring to put the options declaration in the function/constructor itself:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment

```js
function drawES2015Chart({size = 'big', cords = {x: 0, y: 0}, radius = 25} = {}) {
  console.log(size, cords, radius);
  // do some chart drawing
}
```

**Comment by jonathanolson** [comment]
> MDN has an example of using destructuring to put the options declaration in the function/constructor itself

Destructuring has been great, but I wouldn't want to have a 30-line constructor parameters where defaults are specified. Could work nicely for short examples.

**Comment by pixelzoom** [comment]
Comments...

I'm not wild about using a transpiler just to change how we handle options, as proposed in https://github.com/phetsims/phet-core/issues/34#issuecomment-346361113.  I suspect that the costs would outweigh the benefits.

Reminder that we still need to support the equivalent of:

```js
var DEFAULT_OPTIONS = { ... };
...
options = _.extend( {}, DEFAULT_OPTIONS, { ... } );
```

... so the we don't modify DEFAULT_OPTIONS.

**Comment by jonathanolson** [comment]
To me, the options pattern is one of the least important reasons to use es6/transpiler.

I'll have a write-up for the Thurs dev meeting about the features I've used that felt helpful (partially for consideration for using them in sims, and partially so people have will be able to read the chipper/perennial code).

**Comment by samreid** [comment]
> I'm not wild about using a transpiler just to change how we handle options

It's not just about options. The main costs and benefits are outlined in https://github.com/phetsims/chipper/issues/551#issuecomment-347087805

**Comment by pixelzoom** [comment]
I've read through https://github.com/phetsims/chipper/issues/551#issuecomment-347087805, and I'm even less convinced about the transpiler.  The costs listed are massive.

**Comment by samreid** [comment]
Let's unmark this from developer meeting--the primary issue is https://github.com/phetsims/chipper/issues/551 and we can refer to this issue if/when we proceed with that.

**Comment by pixelzoom** [comment]
My recollection from our ES6 discussion is that we decided _not_ to use this pattern, and to stick with the pattern we've been using.  @samreid Is there any reason not to close this issue?

**Comment by samreid** [comment]
This pattern is employed in several places in chipper, you can find some (all?) by searching for ` = options`.  I don't recall if the consensus was "developer preference" or "let's avoid this pattern".  How do you recommend to proceed?

**Comment by pixelzoom** [comment]
I guess we'll have to discuss at developer meeting, since not everyone is clear on what was decided.

The ES6 discussion I referred to above was https://github.com/phetsims/phet-info/issues/82#issuecomment-415184914 (Best Practices for ES6).

**Comment by samreid** [comment]
@jonathanolson: don't use that pattern for sims.  In Node code, we can use lodash, so we should use the same options pattern we use in sims.  I'm not interested in going back and fixing all of them at once, but maybe we can convert them as we go.

**Comment by samreid** [comment]
Self-assigning in case it is easy to look through prior cases to upgrade them.

**Comment by samreid** [comment]
ScrollingChartNode.js has this:

```js
      options = _.extend( {
        width: 190,  // dimensions
        height: 140, // dimensions
        numberHorizontalLines: 3, // Number of horizontal lines (not counting top and bottom)
        numberVerticalLines: 4, // Determines the time between vertical gridlines
        rightGraphMargin: 10, // There is a blank space on the right side of the graph so there is room for the pens
        cornerRadius: 5,
        seriesLineWidth: 2,
        topMargin: 10,
        numberVerticalDashes: 12,
        rightMargin: 10,
        graphPanelOptions: null, // filled in below
        gridLineOptions: null, // filled in below
        graphPanelOverlayOptions: null // filled in below
      }, options );

      // Promote to local variables for readability
      const { width, height, numberHorizontalLines, numberVerticalLines } = options;
```

That seems acceptable to me, but I thought I'd run it past @jonathanolson to be sure.

**Comment by jonathanolson** [comment]
That pattern looks fine to me.

**Comment by samreid** [comment]
That pattern is also used in faradays-law/js/faradays-law/view/MagnetJumpKeyboardListener.js and seems clear.  I'm not seeing a good reason to change these, closing.
