### ISSUE TITLE
phetAllocations are taking too long

### ISSUE THREAD

**Issue by samreid** [phetsims/phet-core#37]
While profiling wave interference, I noticed this in the profiler:

![image](https://user-images.githubusercontent.com/679486/40630341-276d7dee-628f-11e8-869a-15b095facea6.png)

This is in requirejs mode.  But I also noticed that window.phetAllocation is defined for a built sim. Is it being stripped out?  Should we block it with:

```js
assert && phetAllocation && phetAllocation(...)
```

I'm not seeing phetAllocation in the profiler for a built sim, but I'm not sure why.  @jonathanolson what do you think is happening, and how should we proceed?

**Comment by jonathanolson** [comment]
It's stripped out in the uglify step. Generally I'd recommend `grunt --mangle=false` for profiling, since it keeps names but strips out all the things you generally want stripped out for performance.

**Comment by samreid** [comment]
Thanks, I just forgot that `global_defs` would strip things in the minify.
