### ISSUE TITLE
What to do about phetAllocation

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/phet-core#38]
Is this useful to people anymore? Can we replace its usefulness with Chrome devtools?

Would be great to just be able to remove phetAllocation if possible.

**Comment by samreid** [comment]
I requested this issue be assigned to me because I'll consider it while profiling wave interference.

**Comment by samreid** [comment]
Chrome dev tools has been great for Wave Interference, I'll remove this.

**Comment by samreid** [comment]
Removed from all repos, lint-all is passing, we'll reopen if CT or other issues appear.
