### ISSUE TITLE
Array.reverse broken on iOS 12 and Mac Safari 12

### ISSUE THREAD

**Issue by samreid** [phetsims/phet-core#41]
See https://github.com/fanmingfei/array-reverse-ios12.  The webkit bug page says a push has been committed, but we have no way of knowing when Apple will roll this out: https://bugs.webkit.org/show_bug.cgi?id=188794

We have approximately 60 usages of `.reverse()` across our repos.  I have not updated to iOS 12 or Mac Safari 12 so I haven't checked the sims to see this bug in action.  We should decide how to proceed.

**Comment by jonathanolson** [comment]
Having QA test (and being informed of places where reverse() is called) might be a good option.

**Comment by jbphet** [comment]
How about we also help QA determine whether a given platform has the issue?  For instance, we could create a simple page that would print whether the problem exists, so that QA can see first of all if it exists on many of our devices and second which sims break in the presence of the bug.

**Comment by pixelzoom** [comment]
What @jbphet said.  But start with a simple page that only tests `Array.reverse`.   Then if it fails, put in the additional effort to determine which sims break.

**Comment by samreid** [comment]
The link in the initial comment provides a test page and the linked stackoverflow page has another (clearer?) test page.  It looks like refreshing the browser is part of the process required to reproduce the problem.

**Comment by pixelzoom** [comment]
FYI, iOS 12 and Safari 12 were released on 9/17/18. Safari 12 is supported on macOS 10.12 - 10.14.

**Comment by samreid** [comment]
@jonathanolson pointed out that this only affects arrays of primitives, not arrays of objects.  @ariel-phet will check in with the QA team to make sure they are testing on iOS 12 and Mac Safari 12 in the next RCs.

**Comment by ariel-phet** [comment]
Have QA test on iOS 12 with a known problematic safari version next week on all published sims (1 min test) if possible.

**Comment by ariel-phet** [comment]
Closing this issue, we will see what the QA test reveals.

**Comment by samreid** [comment]
Would it be better to leave this issue open and on hold until testing complete?

**Comment by ariel-phet** [comment]
My plan was to open a new issue with relevant information, and the plan to address it IF anything is identified by QA, it is unclear if this is even a problem for us.

Closing, and please leave close @samreid
