### ISSUE TITLE
Enumeration code review

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-core#42]
In https://github.com/phetsims/graphing-quadratics/issues/62, I was asked to convert Graphing Quadratics from string arrays to Enumeration.  Apparently I am the guinea pig, since Enumeration appeared in phet-core on 10/15/18.

Questions, change requests, problems, etc.

- [x] Change `is` to `includes`.  `Align.includes( options.align )` reads much better than `Align.is( options.align )`.  And `includes` will make it much easier to convert from string arrays, where verification is typically something like `[ 'left', 'right', 'center' ].includes( options.align )`, which would become `Align.includes( options.align )`.  It's also difficult to search for `.is(`, which has 2331 occurrences.

- [ ] (UPDATE: see related issue) In the examples and current usages, the name is camel case. But it's an instance/constant, not a class/type.  Are we making an exception to PhET naming conventions here?

- [ ] (UPDATE: see related issue) In the examples and current usages, values are uppercase strings.  Is that a convention?  Should it be enforced? (There is currently no verification.)

- [x] Values should be checked for duplicates. E.g. `new Enumeration( [ 'A', 'B', 'A' ] )` happily succeeds, but is probably not what the programmer intended to do. 

- [x] Enumeration does not behave properly with string comparisons.  E.g.

```
> var Animals = new phet.phetCore.Enumeration( [ 'COW', 'DOG' ] )
undefined
> var cow = 'COW'
undefined
> Animals.is( cow )
true
> Animals.COW === cow
true
```

With a proper enumeration, those last 2 expressions would be `false`.

- [ ] (UPDATE: see related issue)Enumeration silently ignores assignment attempts.  E.g.

```
> Animal.COW = 'dog'
"dog"
> Animal.COW
"cow"
```

The assignment above should be an error.

- [ ] (UPDATE: see related issue)You can apparently change Enumeration's values (which are `@public`, not `@public (read-only)`) after construction.  E.g. 

```
> var Animals = new phet.phetCore.Enumeration( [ 'COW', 'DOG' ] )
undefined
> Animals.is( Animals.COW )
true
> Animals.VALUES
(2) ["COW", "DOG"]
> Animals.VALUES[0] = 'RABBIT'
"RABBIT"
> Animals.VALUES
(2) ["RABBIT", "DOG"]
> Animals.is( Animals.COW )
false
```
What was true has now become false.

- [ ] (UPDATE: see related issue)Enumeration has public field `VALUES`.  Using uppercase for a field name does not match PhET's naming conventions.  Uppercase is for constants.

- [ ] (UPDATE: see related issue)Do we really need the `VALUES` field?  If yes for internal reasons, does it need to be public?

- [x] These 2 assertions need messages, or at least comments about why they are necessary.  

```js
      assert && assert( !_.includes( values, 'VALUES' ) );
      assert && assert( !_.includes( values, 'is' ) );
```

They are necessary because the implementation makes it impossible to use values `'VALUES'` and `'is'`, e.g. `new Enumeration( ( 'VALUES', 'is' ] )`.   That wasn't at all obvious to me until I did this code review.

- [ ] (UPDATE: see related issue)Enumeration doesn't play well with Property validation.  There's no way to use the `valueType` option.  The closest that I could get is using`isValidValue`, like this:

```
> var Animals = new phet.phetCore.Enumeration( [ 'COW', 'DOG' ] )
> var p = new Property( Animals.COW, {
  isValidValue: value => Animals.is( value )
} )
> p.value = Animals.COW
true
> p.value = 1
Uncaught Error: Assertion failed: value failed isValidValue test: 1
> p.value = 'COW'
true
```

And note that last assignment - it should fail !

**Comment by pixelzoom** [comment]
More...

- [ ] Enumeration does not behave properly with string comparisons.  E.g.

```
> var Animals = new phet.phetCore.Enumeration( [ 'COW', 'DOG' ] )
undefined
> var cow = 'COW'
undefined
> Animals.is( cow )
true
> Animals.COW === cow
true
```

With a proper enumeration, those last 2 expressions would be `false`.

- [ ] Enumeration silently ignores assignment attempts.  E.g.

```
> Animal.COW = 'dog'
"dog"
> Animal.COW
"cow"
```

**Comment by pixelzoom** [comment]
- [ ] You can apparently change Enumeration's values (which are `@public`, not `@public (read-only)`) after construction.  E.g. 

```
> var Animals = new phet.phetCore.Enumeration( [ 'COW', 'DOG' ] )
undefined
> Animals.VALUES
(2) ["COW", "DOG"]
> Animals.VALUES[0] = 'RABBIT'
"RABBIT"
> Animals.VALUES
(2) ["RABBIT", "DOG"]
```

**Comment by pixelzoom** [comment]
- [ ] Enumeration has a field `this.VALUES`.  Using uppercase for a field name does not match PhET's naming conventions.  Uppercase is for constants.

**Comment by pixelzoom** [comment]
- [ ] Do we really need the `VALUES` field?  If yes for internal reasons, does it need to be public?

**Comment by pixelzoom** [comment]
- [ ] These 2 assertion need messages, or at least comments about why they are necessary.  

```js
      assert && assert( !_.includes( values, 'VALUES' ) );
      assert && assert( !_.includes( values, 'is' ) );
```

They are necessary because the implementation makes it impossible to use values 'VALUES' and 'is', e.g. `new Enumeration( ( 'VALUES', 'is' ] ).   That wasn't at all obvious to me until I did this code review.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/graphing-quadratics/issues/62#issuecomment-430795603, I decided not to use `Enumeration` in Graphing Lines.  I don't see the benefit over using string arrays, since `Enumeration` incorrectly succeeds in assignments and expressions involving strings.

**Comment by jonathanolson** [comment]
> Change `is` to `includes`

Sounds good, will do.

> In the examples and current usages, the name is camel case. But it's an instance/constant, not a class/type. Are we making an exception to PhET naming conventions here?

It is "acting" like a type defined by being one of the specified string values, so it's named like a type.

> In the examples and current usages, values are uppercase strings. Is that a convention? Should it be enforced? (There is currently no verification.)

This is what others had done, and was convention. Might be good to discuss at dev meeting (I'll tag the issue)

> Values should be checked for duplicates.

Sounds good, will do.

> Enumeration does not behave properly with string comparisons.

It's more of an implementation detail that helps for phet-io. Previous discussions at developer meeting favored this type of enumeration over ones represented by actual objects, since it was easier for phet-io. I'm happy to change this to an object-backed version, would be good to discuss at dev meeting.

> Enumeration silently ignores assignment attempts.

This doesn't happen in strict mode, which we use. It throws a type error

> You can apparently change Enumeration's values

Yup, the array should be frozen also.

> Enumeration has public field VALUES. Using uppercase for a field name does not match PhET's naming conventions. Uppercase is for constants.

That is a constant. Would you prefer lower case for this?

> Do we really need the VALUES field? If yes for internal reasons, does it need to be public?

Yes, it's super helpful to be able to iterate over all possible options in an enumeration.

> These 2 assertions need messages, or at least comments about why they are necessary.

Will do.

> Enumeration doesn't play well with Property validation. There's no way to use the valueType option

`validValues: Animal.VALUES`, or ideally we should be able to handle it with valueType.

**Comment by pixelzoom** [comment]
That sounds great, but should be enforced by Enumeration.

**Comment by samreid** [comment]
> It's more of an implementation detail that helps for phet-io. Previous discussions at developer meeting favored this type of enumeration over ones represented by actual objects, since it was easier for phet-io. I'm happy to change this to an object-backed version, would be good to discuss at dev meeting.

That's my recollection as well.  If we use strings, then serialization is automatic and effortless.  If we define object values for enumerations, then each enumeration type would need to declare its own IO type.  Or maybe we can think of one IO type that works for all Enumerations (by serializing as strings).  I'm interested in investigating this latter idea, it sounds like the best of both worlds.

**Comment by samreid** [comment]
Here's a patch that does the following:
* Moves to object identity instead of string identity--that is, makes `Animals.includes('COW')` return false.
* Introduces `EnumerationIO` to add PhET-iO support like this:

```js
    var SideEnum = new Enumeration( [ 'LEFT', 'RIGHT' ] );

    this.helloProperty = new Property( SideEnum.LEFT, {
      tandem: tandem.createTandem( 'helloProperty' ),
      isValidValue: v =>  SideEnum.includes( v ),
      phetioType: PropertyIO( EnumerationIO( SideEnum ) )
    } );
```

`EnumerationIO` automatically saves and loads Enumeration values.

```
Index: phet-core/js/EnumerationIO.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- phet-core/js/EnumerationIO.js	(date 1541977935000)
+++ phet-core/js/EnumerationIO.js	(date 1541977935000)
@@ -0,0 +1,86 @@
+// Copyright 2016, University of Colorado Boulder
+
+/**
+ * IO type for Property
+ *
+ * @author Sam Reid (PhET Interactive Simulations)
+ * @author Andrew Adare (PhET Interactive Simulations)
+ */
+define( function( require ) {
+  'use strict';
+
+  // modules
+  const Enumeration = require( 'PHET_CORE/Enumeration' );
+  const phetCore = require( 'PHET_CORE/phetCore' );
+  var ObjectIO = require( 'TANDEM/types/ObjectIO' );
+  var phetioInherit = require( 'TANDEM/phetioInherit' );
+  var ArrayIO = require( 'TANDEM/types/ArrayIO' );
+  var StringIO = require( 'TANDEM/types/StringIO' );
+
+  /**
+   * An observable property that triggers notifications when the value changes.
+   * @param {Enumeration} enumeration
+   * @module EnumerationIO
+   * @constructor
+   */
+  function EnumerationIO( enumeration ) {
+    assert && assert( enumeration, 'enumeration must be supplied' );
+    assert && assert( enumeration instanceof Enumeration, 'enumeration must be supplied' );
+
+    /**
+     * @param {Property} property
+     * @param {string} phetioID
+     * @constructor
+     */
+    var EnumerationIOImpl = function EnumerationIOImpl( property, phetioID ) {
+      // assert && assert( !!phetioValueType, 'EnumerationIO needs phetioValueType' );
+      // assert && assert( property, 'Property should exist' );
+      // assert && assert( _.endsWith( phetioID, 'Property' ), 'EnumerationIO instances should end with the "Property" suffix, for ' + phetioID );
+      //
+      // assert && assertInstanceOf( property, phet.axon.Property );
+      ObjectIO.call( this, property, phetioID );
+    };
+
+    return phetioInherit( ObjectIO, 'EnumerationIO', EnumerationIOImpl, {
+      getValues: {
+        returnType: ArrayIO( StringIO ),
+        parameterTypes: [],
+        implementation: function() {
+          return enumeration.values.map( v => v.name );
+        },
+        documentation: 'Gets the current value.'
+      }
+    }, {
+      documentation: 'Observable values that send out notifications when the value changes. This differs from the ' +
+                     'traditional listener pattern in that added listeners also receive a callback with the current value ' +
+                     'when the listeners are registered. This is a widely-used pattern in PhET-iO simulations.',
+
+      // Used to generate the unique parametric typename for each EnumerationIO
+      parameterTypes: [],
+
+      events: [ 'changed' ],
+
+      /**
+       * Encodes a Property instance to a state.
+       * @param {Object} value
+       * @returns {Object} - a state object
+       */
+      toStateObject: function( value ) {
+        return value.name;
+      },
+
+      /**
+       * Decodes a state into a Property.
+       * @param {Object} stateObject
+       * @returns {Object}
+       */
+      fromStateObject: function( stateObject ) {
+        return enumeration[ stateObject ];
+      }
+    } );
+  }
+
+  phetCore.register( 'EnumerationIO', EnumerationIO );
+
+  return EnumerationIO;
+} );
\ No newline at end of file
Index: phet-core/js/Enumeration.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- phet-core/js/Enumeration.js	(revision 1b90ac2fa7529036356173c24ebcaf4d04a5702d)
+++ phet-core/js/Enumeration.js	(date 1541977935000)
@@ -48,13 +48,14 @@
       assert && assert( !_.includes( values, 'includes' ),
         'This is the name of a built-in provided value, so it cannot be included as an enumeration value' );
 
+      // @public {Array.<string>}
+      this.VALUES = [];
       for ( let value of values ) {
         // @public {string}
-        this[ value ] = value;
+        const elm = { name: value };
+        this[ value ] = elm;
+        this.VALUES.push( elm );
       }
-
-      // @public {Array.<string>}
-      this.VALUES = values.slice(); // defensive copy
 
       beforeFreeze && beforeFreeze( this );
       assert && Object.freeze( this );
Index: faradays-law/js/faradays-law/model/FaradaysLawModel.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- faradays-law/js/faradays-law/model/FaradaysLawModel.js	(revision e3e3c4a8c780607ef018cc1fd0c265a6044bc5f9)
+++ faradays-law/js/faradays-law/model/FaradaysLawModel.js	(date 1541978152000)
@@ -11,6 +11,10 @@
 
   // modules
   // var Vector2 = require( 'DOT/Vector2' );
+  const Enumeration = require( 'PHET_CORE/Enumeration' );
+  const EnumerationIO = require( 'PHET_CORE/EnumerationIO' );
+  const Property = require( 'AXON/Property' );
+  const PropertyIO = require( 'AXON/PropertyIO' );
   var BooleanProperty = require( 'AXON/BooleanProperty' );
   var Bounds2 = require( 'DOT/Bounds2' );
   var Coil = require( 'FARADAYS_LAW/faradays-law/model/Coil' );
@@ -37,6 +41,13 @@
 
     // @public (read-only) (Bounds2}
     this.bounds = bounds;
+    var SideEnum = new Enumeration( [ 'LEFT', 'RIGHT' ] );
+
+    this.helloProperty = new Property( SideEnum.LEFT, {
+      tandem: tandem.createTandem( 'helloProperty' ),
+      isValidValue: v => SideEnum.includes( v ),
+      phetioType: PropertyIO( EnumerationIO( SideEnum ) )
+    } );
 
     // @public - Whether the top coil should be shown
     this.topCoilVisibleProperty = new BooleanProperty( false, {
```

As far as I recall, PhET-iO was one of the problematic issues which pushed us to use String Enumerations previously.  Perhaps with this solution we can move forward with Object Enumerations? @jonathanolson thoughts?

**Comment by samreid** [comment]
I decided to commit the proposal for EnumerationIO for the sake of discussion, we can decide whether to keep it or not.

**Comment by pixelzoom** [comment]
@samreid said:
> ... using a `Property`-specific workaround wouldn't support `instanceof` in general like `Animals.COW instanceof Animals`.

I would never expect  to be able to use `Animals.COW instanceof Animals`, since Animals is not a class and Animals.COW is not an instance.  I would expect `Animals.includes( Animals.COW )`.

**Comment by pixelzoom** [comment]
@samreid said:
> Here's a patch that does the following:

Where in Enumeration is the patch applied? What is the significant of var name `elm`?  Is this patch required for EnumerationIO?

**Comment by pixelzoom** [comment]
https://github.com/phetsims/phet-core/issues/42#issuecomment-437714737, @samreid said:
> Here's a patch that does the following: ...

Where in Enumeration should the patch be applied? 
What is the significance of var name `elm`?  
Is this patch required for EnumerationIO?

**Comment by samreid** [comment]
For the sake of discussion, in Java, `enum` is a special kind of class, so this code prints `true`.  I'm fine if we go a different way with JS:

```java
class Main {

  enum Animals { 
    COW, HORSE, CHICKEN
} 
  public static void main(String[] args) {
    System.out.println(Animals.COW instanceof Animals);
  }
}
```

**Comment by pixelzoom** [comment]
`instanceof` works with enumerations in Java because `enum` is part of the language.  That's not the case here, we're rolling our own.  Are you suggesting that we should somehow overload `instanceof`?

**Comment by samreid** [comment]
Here's an actual patch that shows the difference:

```
Index: js/Enumeration.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/Enumeration.js	(revision 714b088a1586e6c3eb25e0774d469effeece134e)
+++ js/Enumeration.js	(date 1541977935000)
@@ -48,13 +48,14 @@
       assert && assert( !_.includes( values, 'includes' ),
         'This is the name of a built-in provided value, so it cannot be included as an enumeration value' );
 
+      // @public {Array.<string>}
+      this.VALUES = [];
       for ( let value of values ) {
         // @public {string}
-        this[ value ] = value;
+        const elm = { name: value };
+        this[ value ] = elm;
+        this.VALUES.push( elm );
       }
-
-      // @public {Array.<string>}
-      this.VALUES = values.slice(); // defensive copy
 
       beforeFreeze && beforeFreeze( this );
       assert && Object.freeze( this );
```

> What is the significance of var name elm?

My undergrad CS teacher once used the word "elm" as an abbreviation for "element".  We should choose a better variable name if we move forward with this pattern.

**Comment by samreid** [comment]
> Are you suggesting that we should somehow overload instanceof?

I don't think we could overload the `instanceof` operator generally, but we could add a special case to `Property.valueType` to handle enumerations if that seems better than using `validValues: MyEnumeration.VALUES` or `isValidValue: v=>MyEnumeration.includes(v)`

**Comment by jonathanolson** [comment]
If we're objectifying enumeration values, we'll also want to provide each object with a `toString()` method.

In the past, we've used enumeration values as object keys (since they were both strings), and providing `toString()` will allow this to work as before, e.g.:

```js
map[ SideEnum.LEFT ] = 5;

map[ enumValue ];
```

**Comment by samreid** [comment]
@jonathanolson and I discussed this and decided to move forward with objectifying enumeration values using the strategy proposed in https://github.com/phetsims/phet-core/issues/42#issuecomment-437714737.  I'll do so shortly (with the proposed toString implementation).

**Comment by samreid** [comment]
In the preceding commits, Enumeration has been changed to use Object values instead of String values, and I added tests to make sure it is working properly and to make sure `toString` works as desired.  Reassigning to @jonathanolson and @pixelzoom to review this part.

**Comment by pixelzoom** [comment]
I'll be happy to review this after work is considered complete and @jonathanolson has reviewed it.

**Comment by jonathanolson** [comment]
Looks good to me.

**Comment by pixelzoom** [comment]
The best way for me to review this is to use it.  I have a couple of string enumerations in Gas Properties that I'll try converting to Enumeration.   It may be awhile before I get to this.

**Comment by pixelzoom** [comment]
@samreid @jonathanolson I'm assuming that it's OK to remove the meeting:developer label.  Restore it if there's a reason to discuss.

**Comment by jonathanolson** [comment]
There were at least a few of your review notes that would benefit from group discussion, but it can be handled later.

**Comment by pixelzoom** [comment]
Most of the checklist item in https://github.com/phetsims/phet-core/issues/42 are still unchecked. @samreid please check the ones that have been addressed so that I know what I'm reviewing, then assign back to me.

**Comment by samreid** [comment]
The part that would be good to review is where we moved to object equality instead of string equality in https://github.com/phetsims/phet-core/commit/27c1c5d0dc95781f2d84893e82fe1769d151c545 and the corresponding test https://github.com/phetsims/phet-core/commit/2e54db083eb309bcb4b7cec0bd650c53a19156df

**Comment by pixelzoom** [comment]
I've used Enumeration in gas-properties, see above commit.  

Object equality seems to be working nicely. But I can still modify `VALUES`, it needs to be frozen.

Example of `Property` value validation boilerplate is shown below. What would `phetioType` be?

```js
      // @public the particle type that will be dispensed by the bicycle pump
      this.particleTypeProperty = new Property( ParticleTypeEnum.HEAVY, {
        isValidValue: value => ParticleTypeEnum.includes( value )
      } );
```

Back to @samreid.

**Comment by samreid** [comment]
You may prefer to use:
`validValues: ParticleTypeEnum.VALUES`

instead of 
`isValidValue: value => ParticleTypeEnum.includes( value )`

The phetioType would be `phetioType: EnumerationIO(ParticleTypeEnum)`.  I hate to use the term "guinea pig", but this is a new type and hasn't been used in practice yet.

**Comment by samreid** [comment]
> Are you suggesting that we should somehow overload instanceof?

Or each Enumeration could internally create a type, then create values as instances of the type, then `instanceof` should work...

**Comment by jonathanolson** [comment]
> Or each Enumeration could be a type, then create values as instances of the type, then instanceof should work...

That sounds potentially nice. You'd want to support subclassing the class, so it might be a bit tricky to set up though.

**Comment by samreid** [comment]
I'm going to split out remaining features into new issues to help us divide and conquer.  Look out below for related issues ⬇️

**Comment by samreid** [comment]
All outstanding work has been moved to new issues, I recommend we close this parent issue and continue in the child issues, @pixelzoom sound OK?

**Comment by pixelzoom** [comment]
@samreid said:
> All outstanding work has been moved to new issues, I recommend we close this parent issue and continue in the child issues, @pixelzoom sound OK?

In Slack dev discussion today, it was noted that this is not the case.  There are outstanding issues (e.g. lack of `valueType` support) with no obvious "related issue".   So reopening until all of the checklist items in this issue have been addressed, or have a specific issue number next to them.

**Comment by pixelzoom** [comment]
Assigning to @jonathanolson to complete, since he was the author that I was doing the review for.

**Comment by samreid** [comment]
Sam Reid [3:13 PM]
https://github.com/phetsims/phet-core/issues/49 was linked near the bottom of https://github.com/phetsims/phet-core/issues/42
And it quotes the same `- [ ] Enumeration doesn't play well with Property validation.`  item

Michael Kauzmann [3:15 PM]
That seems like a reasonable outcome. and like it handles the topic. We are now just in a better place to improve on the previous solution (because of ValidatorDef)

**Comment by pixelzoom** [comment]
> #49 was linked near the bottom of #42
> And it quotes the same - [ ] Enumeration doesn't play well with Property validation. item

There are 7 occurrences of "(UPDATE: see related issue)" next to the review items that I identified. 
Feel free to replace these with specific item numbers.  When ever item has been addressed or clearly moved to another issue, then we can close this issue.

**Comment by pixelzoom** [comment]
"(UPDATE: see related issue)" edits were made by @samreid on 12/8/18.

**Comment by pixelzoom** [comment]
A new item came up in today's Slack dev discussion:

- [ ] Enumeration values are object literals of the form `{ name:string, toString:function }`.  There were many questions about this. There is no information about the visibility of fields.  Are the objects intended to be opaque? Is it OK to explicitly call `toString`? What is the purpose of `name`, since it's not used anywhere in Enumeration?  @zepumph suggested we should consider having a first-class type like `EnumerationValue` to properly document. @pixelzoom said that would be OK if it `EnumerationValue` were private to `Enumeration`.

**Comment by jessegreenberg** [comment]
Related to https://github.com/phetsims/phet-core/issues/42#issuecomment-474591114, should public `this.KEYS` be removed if we shouldn't be using strings?

**Comment by samreid** [comment]
Agreed, it looks like `KEYS` are unused and should be removed.

**Comment by pixelzoom** [comment]
Labeling for dev meeting to figure out how to take this issue to the finish line.

**Comment by pixelzoom** [comment]
3/5/20 dev meeting:  @jonathanolson will get on it.

**Comment by jonathanolson** [comment]
> Agreed, it looks like KEYS are unused and should be removed.

KEYS is now used in EnumerationIO, maybe it should be kept?

We have usages and use cases where it makes sense for `value.name` and `value.toString()` to be public, so I've marked them as such.

> we should consider having a first-class type like EnumerationValue to properly document

That seems tricky to have specifically for documentation, as Enumeration.byMap wouldn't be using EnumerationValue, so we'd presumably have to have the same `value.name = ` setter and duplicate code/documentation.

I don't immediately see any further changes that are necessary, but I'm open to discussion about what should be done.

**Comment by jonathanolson** [comment]
Also saw that the original top issue description may have been updated, I was just looking at things since the issue was re-opened. I'll scan those.

**Comment by pixelzoom** [comment]
The 2 things that @jonathanolson called out in the previous comment were proposed by @samreid and @zepumph respectively.  So I'm assigning to them in case they want to discuss further.

**Comment by pixelzoom** [comment]
The 2 things that @jonathanolson called out in https://github.com/phetsims/phet-core/issues/42#issuecomment-597186685 were proposed by @samreid and @zepumph respectively.  So I'm assigning to them in case they want to discuss further.    I don't have any other strong feelings on Enumeration, I'd just like to see the review completed.

**Comment by jonathanolson** [comment]
> (UPDATE: see related issue) In the examples and current usages, the name is camel case. But it's an instance/constant, not a class/type. Are we making an exception to PhET naming conventions here?

It doesn't seem like an exception, as it's defining a type. Classes or types also are object instances in JS. see https://github.com/phetsims/phet-core/issues/43

> (UPDATE: see related issue) In the examples and current usages, values are uppercase strings. Is that a convention? Should it be enforced? (There is currently no verification.)

That's convention, and I think it's up to developers whether we want to enforce it (presumably could be done in Enumeration.js itself, but I'd like to wait to see if it's desired first).

> (UPDATE: see related issue)Enumeration silently ignores assignment attempts. E.g.

Does not seem to happen anymore (at least in strict mode, which is all of our modules):
```js
( () => {
  'use strict';
  const Animals = phetCore.Enumeration.byKeys( [ 'COW', 'DOG' ] );
  Animals.COW = 'dog';
} )();
```
gives
```
VM1692:5 Uncaught TypeError: Cannot assign to read only property 'COW' of object '#<Enumeration>'
```

> (UPDATE: see related issue)You can apparently change Enumeration's values (which are @public, not @public (read-only)) after construction. E.g.

Does not seem to happen anymore:
```js
( () => {
  'use strict';
  const Animals = phetCore.Enumeration.byKeys( [ 'COW', 'DOG' ] )
  console.log( Animals.includes( Animals.COW ) );
  console.log( Animals.VALUES );
  Animals.VALUES[0] = 'RABBIT';
  console.log( Animals.VALUES );
  console.log( Animals.includes( Animals.COW ) );
} )();
```
gives
```
VM1702:6 Uncaught TypeError: Cannot assign to read only property '0' of object '[object Array]'
```

> (UPDATE: see related issue)Enumeration has public field VALUES. Using uppercase for a field name does not match PhET's naming conventions. Uppercase is for constants.

I would like to see this changed to `values`.

> (UPDATE: see related issue)Do we really need the VALUES field? If yes for internal reasons, does it need to be public?

Oh yes, all the time.

> (UPDATE: see related issue)Enumeration doesn't play well with Property validation. There's no way to use the valueType option. The closest that I could get is usingisValidValue, like this:

We have `EnumerationProperty`, AND the last example should work, 

```js
const Animals = phetCore.Enumeration.byKeys( [ 'COW', 'DOG' ] )
const p = new axon.Property( Animals.COW, {
  isValidValue: value => Animals.includes( value )
} );
p.value = Animals.COW;
p.value = 1; // Assertion failed: value failed isValidValue: 1
p.value = 'COW'; // Assertion failed: value failed isValidValue: COW
```

**Comment by jonathanolson** [comment]
So... I'd like to change `KEYS` and `VALUES` to `keys` and `values` respectively, that would probably be good to discuss briefly at dev meeting. Otherwise I believe everything else is handled, unless @samreid or @zepumph want to recommend further changes.

**Comment by pixelzoom** [comment]
>> (UPDATE: see related issue) In the examples and current usages, the name is camel case. But it's an instance/constant, not a class/type. Are we making an exception to PhET naming conventions here?
> It doesn't seem like an exception, as it's defining a type. Classes or types also are object instances in JS. see #43

Indeed, we decided long ago to use class-like names for enums.

> > (UPDATE: see related issue) In the examples and current usages, values are uppercase strings. Is that a convention? Should it be enforced? (There is currently no verification.)
> That's convention, and I think it's up to developers whether we want to enforce it (presumably could be done in Enumeration.js itself, but I'd like to wait to see if it's desired first).

Looks like it's more than a convention, it's enforced on line 99:

```js
assert && keys.forEach( value => assert( /^[A-Z][A-Z0-9_]*$/g.test( value ),
      'Enumeration values should be uppercase alphanumeric with underscores and begin with a letter' ) );
```

Most of the other things in https://github.com/phetsims/phet-core/issues/42#issuecomment-597197956 are indeed things that were addressed long ago.  That's the problem with not resolving review issues promptly.

**Comment by jessegreenberg** [comment]
After discussing 3/12/20, no one had a strong preference one way or the other and so we are going to drop this point. Everything else has been addressed for this issue so we can close.

**Comment by samreid** [comment]
My thoughts from the discussion:

I don't feel strongly and would be OK with upper or lowercase `keys` and `values`.  That being said, it seems we are treating enumerations such as `Animals` as types, and hence upper-case makes sense.  Also, if we want the enumeration values such as `Animals.COWS` to be upper-case, it makes sense to treat `KEYS` on equal footing.
