### ISSUE TITLE
Should we assert that Enumeration value texts are UPPERCASE?

### ISSUE THREAD

**Issue by samreid** [phetsims/phet-core#44]
In https://github.com/phetsims/phet-core/issues/42#issue-371259394 @pixelzoom said:

> In the examples and current usages, values are uppercase strings. Is that a convention? Should it be enforced? (There is currently no verification.)

**Comment by samreid** [comment]
@jonathanolson said:

> This is what others had done, and was convention. Might be good to discuss at dev meeting (I'll tag the issue)

**Comment by samreid** [comment]
I said:

> I had been using uppercase strings as I understood that to be the agreed-upon convention for our team.  For example, in Wave Interference:

```js
  const BarrierTypeEnum = {
    NO_BARRIER: 'NO_BARRIER',
    ONE_SLIT: 'ONE_SLIT',
    TWO_SLITS: 'TWO_SLITS'
  };
```

**Comment by samreid** [comment]
@pixelzoom said:

> That sounds great, but should be enforced by Enumeration.

**Comment by samreid** [comment]
In the preceding commit, I added a regex test for each enumeration value and a unit test to make sure the regex test is working.  @pixelzoom can you please review at your convenience?  The regex test is:

```js
      assert && keys.forEach(
        value => assert( value.match( /^[A-Z][A-Z0-9_]*$/g ),
          'Enumeration values should be uppercase alphanumeric with underscores and begin with a letter' )
      );
```

**Comment by pixelzoom** [comment]
The test you have works fine.  I would've used `/^[A-Z][A-Z0-9_]*$/g.test( value )`, since it returns true/false.  Your decision on whether the change it.

**Comment by samreid** [comment]
Thanks, I changed it to use regex.test.  Back to you for microreview.

**Comment by pixelzoom** [comment]
👍
