### ISSUE TITLE
Enumeration values should be immutable

### ISSUE THREAD

**Issue by samreid** [phetsims/phet-core#46]
From #42 @pixelzoom said:

> - [ ] You can apparently change Enumeration's values (which are `@public`, not `@public (read-only)`) after construction.  E.g. 

```
> var Animals = new phet.phetCore.Enumeration( [ 'COW', 'DOG' ] )
undefined
> Animals.is( Animals.COW )
true
> Animals.VALUES
(2) ["COW", "DOG"]
> Animals.VALUES[0] = 'RABBIT'
"RABBIT"
> Animals.VALUES
(2) ["RABBIT", "DOG"]
> Animals.is( Animals.COW )
false
```
> What was true has now become false.

**Comment by samreid** [comment]
@jonathanolson said:

> Yup, the array should be frozen also.

**Comment by samreid** [comment]
@pixelzoom said:

> Object equality seems to be working nicely. But I can still modify VALUES, it needs to be frozen.

**Comment by samreid** [comment]
I tested that modifying VALUES indeed throws an error when Object.freeze is set.  I added a unit test for this as well.  @pixelzoom can you please review?

**Comment by pixelzoom** [comment]
`VALUES` is still modifiable, I see no evidence that it has been frozen.  And the unit test isn't testing this.

```
> var Animals = new phet.phetCore.Enumeration( [ 'COW', 'DOG' ] )
undefined
> Animals.VALUES[0]
{name: "COW", toString: ƒ}
> Animals.VALUES[0] = 1
1
> Animals.VALUES[0]
1
```

**Comment by jonathanolson** [comment]
> Yup, the array should be frozen also.

As in, it SHOULD be done, but it isn't. I added the freezes in the above commit.

Now attempts to modify them properly error:

![enumeration-values](https://user-images.githubusercontent.com/480878/49554224-6eb7a480-f8b8-11e8-9bfc-4a31b82c129a.PNG)

**Comment by pixelzoom** [comment]
And over in https://github.com/phetsims/phet-core/issues/48#issuecomment-444539223, @samreid had said:
> Values are frozen as described in #46, unless I'm misunderstanding something. Please clarify.

So I don't know who to believe :)

**Comment by samreid** [comment]
The miscommunication was reassigning the entire `VALUES` array vs reassigning elements of the `VALUES` array.  Sounds like both are frozen now.  Closing.
