### ISSUE TITLE
Enumeration VALUES casing?

### ISSUE THREAD

**Issue by samreid** [phetsims/phet-core#47]
From #42 @pixelzoom said:

> - [ ] Enumeration has public field `VALUES`.  Using uppercase for a field name does not match PhET's naming conventions.  Uppercase is for constants.

**Comment by samreid** [comment]
@jonathanolson said:

> That is a constant. Would you prefer lower case for this?

**Comment by samreid** [comment]
I prefer `Enumeration.VALUES`. That is, having `Enumeration` cased as if it were a type, and having `VALUES` as if it were a static constant on that type.  @pixelzoom back to you.

**Comment by pixelzoom** [comment]
OK with me.
