### ISSUE TITLE
Does Enumeration need VALUES?  Does it need to be public?

### ISSUE THREAD

**Issue by samreid** [phetsims/phet-core#48]
From #42 @pixelzoom said:

> - [ ] Do we really need the `VALUES` field?  If yes for internal reasons, does it need to be public?

**Comment by samreid** [comment]
@jonathanolson said:

> Yes, it's super helpful to be able to iterate over all possible options in an enumeration.

**Comment by samreid** [comment]
I agree it is useful to iterate over enumeration values, and this is also helpful in Property validation via `validValues: MyEnumeration.VALUES`.  @pixelzoom sound ok?

**Comment by pixelzoom** [comment]
OK.  But `VALUES` needs to be frozen.

**Comment by samreid** [comment]
Values are frozen as described in https://github.com/phetsims/phet-core/issues/46, unless I'm misunderstanding something.  Please clarify.

**Comment by pixelzoom** [comment]
I reviewed this issue before seeing #46, where I see that `VALUES` is now frozen.  Closing.
