### ISSUE TITLE
How should we use Property validation for Enumerations?

### ISSUE THREAD

**Issue by samreid** [phetsims/phet-core#49]
From #42 @pixelzoom said:

> - [ ] Enumeration doesn't play well with Property validation.  There's no way to use the `valueType` option.  The closest that I could get is using`isValidValue`, like this:

```
> var Animals = new phet.phetCore.Enumeration( [ 'COW', 'DOG' ] )
> var p = new Property( Animals.COW, {
  isValidValue: value => Animals.is( value )
} )
> p.value = Animals.COW
true
> p.value = 1
Uncaught Error: Assertion failed: value failed isValidValue test: 1
> p.value = 'COW'
true
```

> And note that last assignment - it should fail !

**Comment by samreid** [comment]
@jonathanolson said:

> validValues: Animal.VALUES, or ideally we should be able to handle it with valueType.

**Comment by samreid** [comment]
I said:

> We could introduce a special case so that `Property` can use `valueType` for `Enumeration`, but using a `Property`-specific workaround wouldn't support `instanceof` in general like `Animals.COW instanceof Animals`.  Would that be confusing, or should we proceed with a `Property`-specific workaround?

**Comment by samreid** [comment]
@pixelzoom replied:

> I would never expect  to be able to use `Animals.COW instanceof Animals`, since Animals is not a class and Animals.COW is not an instance.  I would expect `Animals.includes( Animals.COW )`.

**Comment by samreid** [comment]
For the sake of discussion, in Java, `enum` is a special kind of class, so this code prints `true`.  I'm fine if we go a different way with JS:

```java
class Main {

  enum Animals { 
    COW, HORSE, CHICKEN
} 
  public static void main(String[] args) {
    System.out.println(Animals.COW instanceof Animals);
  }
}
```

**Comment by samreid** [comment]
@pixelzoom said:

> `instanceof` works with enumerations in Java because `enum` is part of the language.  That's not the case here, we're rolling our own.  Are you suggesting that we should somehow overload `instanceof`?

**Comment by samreid** [comment]
I don't think we could overload the `instanceof` operator generally, but we could add a special case to `Property.valueType` to handle enumerations if that seems better than using `validValues: MyEnumeration.VALUES` or `isValidValue: v=>MyEnumeration.includes(v)`

**Comment by samreid** [comment]
@pixelzoom said:

> Example of `Property` value validation boilerplate is shown below. What would `phetioType` be?

```js
      // @public the particle type that will be dispensed by the bicycle pump
      this.particleTypeProperty = new Property( ParticleTypeEnum.HEAVY, {
        isValidValue: value => ParticleTypeEnum.includes( value )
      } );
```

**Comment by samreid** [comment]
I replied:

You may prefer to use:
`validValues: ParticleTypeEnum.VALUES`

instead of 
`isValidValue: value => ParticleTypeEnum.includes( value )`

The phetioType would be `phetioType: EnumerationIO(ParticleTypeEnum)`.  I hate to use the term "guinea pig", but this is a new type and hasn't been used in practice yet.

**Comment by samreid** [comment]
> Are you suggesting that we should somehow overload instanceof?

Or each Enumeration could be a type, then create values as instances of the type, then `instanceof` should work...

**Comment by samreid** [comment]
@jonathanolson said:

> That sounds potentially nice. You'd want to support subclassing the class, so it might be a bit tricky to set up though.

I think I should create a sub-sub issue about `instanceof`.

**Comment by samreid** [comment]
I created a sub-issue about `instanceof`.  Hence this issue will just be about Property validation.  The proposal is to use `validValues: MyEnumeration.VALUES`.  @pixelzoom sound OK?

**Comment by pixelzoom** [comment]
I'm OK with using `validValues: MyEnumeration.VALUES`, if that field is frozen.   But I also think that using `MyEnumeration.includes( value )` is acceptable, especially in circumstances where validation might involve more than simply inclusion in an Enumeration.

**Comment by samreid** [comment]
Sounds good, can this issue be closed?

**Comment by jonathanolson** [comment]
No further input.
