### ISSUE TITLE
namespace keys are not verified for inner classes

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-core#52]
Over in https://github.com/phetsims/sun/issues/429, I noted this in `ComboBox`, namespace registration for inner class `ComboBoxItemNode`:

`sun.register( 'ComboBox.ItemNode', ComboBoxItemNode );`

It should be:

`sun.register( 'ComboBox.ComboBoxItemNode', ComboBoxItemNode );`

This error (introduced on 12/7/2016) is not being detected. Looking at checkNamespaces.js, I see no support for inner classes. 

Assigning to @ariel-phet to prioritize and assign.  The original author of checkNamespaces.js was @jonathanolson.  Most recent commits were by @jonathanolson and @samreid.

**Comment by zepumph** [comment]
I added these two lines to the top of Namespace.register:
```js
      var keyParts = key.split( '.' );
      key !== 'FastArray' && typeof value === 'function' && value.name && assert && assert( keyParts[ keyParts.length - 1 ] === value.name, 'incorrect naming' );

```

And it seemed to work as expected. Notice the edge case for dot's "FastArray". Otherwise It caught the ComboBox error and I didn't see anything else.

**Comment by zepumph** [comment]
Scratch that I found a few more issues:

- [x] ComboBoxItemNode (now) fixed
- [x] SkaterSamplesNode
- [x] ScaleSlider

**Comment by zepumph** [comment]
I think we should clean up this assertion and add it in, as it helped to find a few registration malformities. Cleaned up I wonder if we could make it look like:

```js
if ( assert && typeof value === 'function' && typeof value.name === 'string' && key !== 'FastArray' ) {
  var keyParts = key.split( '.' );
  assert( keyParts[ keyParts.length - 1 ] === value.name, 'incorrect naming' );
}
```

I really don't like the "FastArray" check in there. It seems out of place. 

I think also we could make the argument that this was only a problem in 3 places (one of which was just me being stupid), and so perhaps since I fixed the above code it is enough.

**Comment by samreid** [comment]
I thought @jonathanolson had recently mentioned that we may remove FastArray? But I may be thinking of something else.

**Comment by ariel-phet** [comment]
I feel like we should discuss this at 01/10/19 dev meeting since checking for namespace collisions seems worthwhile and there appear to be some open questions in the discussion above.

**Comment by samreid** [comment]
Perhaps we can iterate over the keys in a registered requirejs object, see if any have type `function` or `class` and start with an uppercase letter + lowercase letter.  Then check if they are namespaced correctly?

**Comment by samreid** [comment]
I haven't made time for this issue yet, and would like to check in with @ariel-phet about it.  I also recall we discussed this topic at a developer meeting and concluded that not all inner classes need to be namespaced.  I'm happy if you want to schedule it for consideration at an upcoming dev meeting.

**Comment by ariel-phet** [comment]
Putting back on dev meeting, perhaps someone else can tackle

**Comment by Denz1994** [comment]
Discussed at dev meeting: 09/19/19

Not all types need to be name spaced, but if they should be done correctly. This is only an issue during namespace collisions and may be an issue for third parties. 

Namespace only knows of nested types based on the dot notation. 

Code review checklist has been adjusted to make sure the dev includes the dot for the inner class.

We will close this issue and make sure the dev is careful to use the appropriate dot notation for name-spacing.
