### ISSUE TITLE
Guard against shadowing for mixins and traits

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/phet-core#54]
This came out of discussion in https://github.com/phetsims/phet-info/issues/92 and https://github.com/phetsims/phet-info/issues/88. When using mixin/trait pattern there is no guard against accidentally overriding functions in the mixin/trait.

It was recommended that someone examine our mixin/trait pattern and recommend a solution for this. Adding to developer meeting to discuss with @ariel-phet priority and who should investigate.

**Comment by jessegreenberg** [comment]
I also found https://github.com/phetsims/phet-core/issues/29, which is very related. Though I think discussion on the 2/11/19 sofware design patterns meeting was more concerned with accidental function overloading than accidentally replacing properties.

**Comment by samreid** [comment]
Accidental shadowing can also occur for `class extends` and `inherit`.  Perhaps we can find a solution that helps us address these cases in addition to mixins/traits.  Do we ever have intentional shadowing?

**Comment by Denz1994** [comment]
Dev Meeting 02/14/19

AP: Return to dev meeting with a recommendation to handle accidental overrides.

SR: Consider using ES6 proxy to catch shadowing. May not be compatible with all browsers.

JO: A better pattern for checking for existence before the mixin may avoid proxy usage.

**Comment by jessegreenberg** [comment]
Discussed during core hours 2/25/19, we would like to guard against shadowing for methods and fields when using the mixin/trait pattern. If the solution to this will work with `inherit` that is great, but since we are generally writing new code with `extends` now, it isn't worth spending much time on that.

**Comment by jessegreenberg** [comment]
Part of this might include creating a more concrete `trait` file that defines our pattern for this. Right now the pattern for using `mixin`/`trait` involves re-writing the code each time for modifying the prototype and everything else.

**Comment by pixelzoom** [comment]
This came up again in the context of https://github.com/phetsims/sun/issues/257.  We are using mixin/trait heavily for scenery and a11y. Now we're adding it to UI components in sun and scenery-phet.  We need to guard against accidentally overriding properties of the host class. 

Something as simple as this might do the job:

```js
function assertVerifyMixinProperties( object, properties ) {
   properties.forEach( property => 
    assert( !object.hasOwnProperty( property ), `mixin or trait will override host property: ${property}` )
}

// In sun.EnabledComponent
assert && assertPropertyOverrides( this, [ 'enabledProperty', 'setEnabled', 'getEnabled', 'disposeEnabledComponent', '_disposeEnabledComponent'  ] );
```

Labeling for developer meeting.

**Comment by samreid** [comment]
I think @zepumph pointed out that `hasOwnProperty` is not sufficient to determine the existence of properties within the prototype chain.

**Comment by pixelzoom** [comment]
Right, hasOwnProperty is not sufficient.  We need to look all the way up the class hierarchy.  Or I should say "up the prototype chain", since JavaScript really doesn't have classes.

**Comment by zepumph** [comment]
`assertHasOwnProperties.js` was just created over in https://github.com/phetsims/sun/issues/257 and holds the logic that will likely be needed here for a general solution to test that items don't yet exist. Perhaps we can turn that into a function that returns a boolean so that we can use it in either direction.

**Comment by zepumph** [comment]
- [ ] What ever is decided here should be implemented in `EnabledComponent` immediately to make sure that `this` doesn't yet have an `enabledProperty`.

**Comment by pixelzoom** [comment]
>  Perhaps we can turn that into a function that returns a boolean so that we can use it in either direction.

I considered that when I suggested `assertHasOwnProperties` over in phetsims/sun#257, and then proposed `assertVerifyMixinProperties ` in https://github.com/phetsims/phet-core/issues/54#issuecomment-605197817.  But I think we will want an assertion failure that identifies a specific property, not just "some property already exists in host class".

**Comment by jonathanolson** [comment]
So we're looking for a library function that scans a specific object's prototype to determine if it has a definition? Then ideally a helper function that will scan a list of property names and error out nicely if they exist?

I'm happy to write that and provide it, let me know.

**Comment by zepumph** [comment]
@jonathanolson I think part of the appeal is to check non prototype elements to. For example making sure that `this.enabledProperty` isn't defined before EnabledComponent.initializeEnabledComponent` sets it.  I can't really think of a way to implement that in a way that isn't manual in each `initialize*` method. 

Are we interested in doing this for the prototype methods too? Perhaps this could be a replacement for the `extend` function in mixins. And part of the prototype extension is to make sure that it isn't blowing anything away. 

@jonathanolson I would say go for it and we can take it for a test drive.

**Comment by jessegreenberg** [comment]
Visited this issue 5/21/20 developer meeting and still think this would be useful, particularly since a11y related code is leveraging trait/mixin pattern more.

**Comment by samreid** [comment]
I'd like to understand how this problem would appear when using the class-factory pattern identified in https://github.com/phetsims/phet-info/issues/143

**Comment by jonathanolson** [comment]
This would be similar to the problem of "how do you know if you're overwriting a method/property with normal inheritance", which we currently don't auto-detect.

**Comment by jonathanolson** [comment]
In dev meeting, we're going to put this on hold until https://github.com/phetsims/phet-info/issues/143 is completed.

**Comment by samreid** [comment]
TypeScript now catches shadowing and will error unless you annotate as `override`. Closing.
