### ISSUE TITLE
Enumeration documentation is out of date

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/phet-core#56]
There was a time when `Enumeration` API involved strings, so that 
```js
const CardinalDirection = new Enumeration( [ 'NORTH', 'SOUTH', 'EAST', 'WEST' ] );
```
would set up 
```
 *   CardinalDirection.NORTH; // 'NORTH'
 *   CardinalDirection.SOUTH; // 'SOUTH'
 *   CardinalDirection.EAST; // 'EAST'
 *   CardinalDirection.WEST; // 'WEST'
 *   CardinalDirection.VALUES; // [ 'NORTH', 'SOUTH', 'EAST', 'WEST' 
```
(example taken directly from file documentation)

But it has changed so that we avoid working with strings entirely. Now `Enumeration` works with opaque objects, so the above example in documentation should be changed to reflect this.

This is also true for `includes`, which does not take a String, but requires the Enumeration value object.
```
 *   CardinalDirection.includes( 'NORTH' ); // true
```

should be changed to 
```
 *   CardinalDirection.includes( CardinalDirection.NORTH ); // true
```

**Comment by pixelzoom** [comment]
There should probably be deleted, because they are just plain wrong:

```js
 *   CardinalDirection.NORTH; // 'NORTH'
 *   CardinalDirection.SOUTH; // 'SOUTH'
 *   CardinalDirection.EAST; // 'EAST'
 *   CardinalDirection.WEST; // 'WEST'
```

**Comment by jessegreenberg** [comment]
I updated the examples in the documentation and removed everything that indicated Enumeration values were strings. This seems straight forward enough to just close, but @pixelzoom @jonathanolson feel free to take a look or change anything.
