### ISSUE TITLE
mergeTest.js introduces a dependency on axon in phet-core

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-core#58]
Related to https://github.com/phetsims/phet-info/issues/91, the creation of merge.js.

While working on another issue, I noticed that mergeTest.js contains a dependency on axon:

```js
9   var Property = require( 'AXON/Property' );
```

I believe that it's generally problematic for phet-core to dependent on axon (circular dependency?) And all other `require` statements in phet-core .js files uses `PhET_CORE` exclusively.   Perhaps this constraint doesn't need to apply to unit tests, but I thought I'd mention it.

**Comment by mbarlow12** [comment]
Thanks for spotting this; I'll update the tests to use object literals instead as that will be more generic. The recent changes to merge on Fri. appear to allow for that.

**Comment by ariel-phet** [comment]
Since Michael has now moved on, reassigning to @pixelzoom to see if this can be closed.

**Comment by pixelzoom** [comment]
Looks good, closing.
