### ISSUE TITLE
assertMutuallyExclusiveOptions could use more doc/examples

### ISSUE THREAD

**Issue by zepumph** [phetsims/phet-core#62]
From https://github.com/phetsims/scenery-phet/issues/451, I am thinking that I should use this function in `NumberControl`, but I don't really understand what it does just from looking at it. I will add doc as I learn about it for my usage.

**Comment by zepumph** [comment]
Committed above. @samreid does that look reasonable to you?

**Comment by samreid** [comment]
These examples look great, thanks!  I realized I had done something similar in phet-core/js/assertMutuallyExclusiveOptionsTests.js but hadn't referenced it in phet-core/js/assertMutuallyExclusiveOptions.js.  Ready to close, but @zepumph feel free to reopen if you want to make changes in light of the *Tests.js file.
