### ISSUE TITLE
Use PHET_CORE/merge instead of _.extend

### ISSUE THREAD

**Issue by zepumph** [phetsims/phet-core#71]
This issue is to discuss and implement the conversion of our extending pattern of options from using `_.extend()` to `merge()`.  At today's design pattern meeting, there were no objections towards moving to a "always use merge" pattern. 

Action items:
- [x] Make sure all developers know about this change.
- [x] Update documentation to reflect this change in pattern.
- [x] Investigate updating previous usages to use `merge` instead of `_.extends`.
  * The first here is a blanket conversion from `_.extends` to `require( 'PHET_CORE/merge')`
  * If there aren't many problems, then we can worry about making it right.

**Comment by zepumph** [comment]
I posted to the dev channel:

>I'm working on https://github.com/phetsims/phet-core/issues/71, and RE: the first checkbox, here is your PSA:
In new code, use merge instead of _.extend in call cases where you can require it.

**Comment by zepumph** [comment]
I made a way to automatically convert usages of `_.extend` to `merge`, including adding the import. It is convoluted, and probably wasn't worth the time, but I'm happy, because. . . well . . . automation. 

Here are the steps to reproduce:
1. pull all repos
2. Make sure you have NO working copy changes in any of the repos you are touching.
2. go to chipper/eslint/eslintrc.js and turn the `no-extend` rule to `2` (error). 
3. go to CHIPPER/lint.js and turn on the `fix` option, and uncomment the fix outputter
4. go `active-runnables` or your favorite data list, and edit the repos you want this to apply to. 
5. Add the following script to a file called `git/sandbox/js.js` or another scrap file, just make just to change the path below. This script will add the merge require statement for each filepath in a file called `test.txt`.
   <details>

   ```js
   ( async () => {

	  const cp = require( 'child_process' );
	  const execute = require( '../perennial/js/common/execute' );
	  const fs = require( 'fs' );

	  const x = fs.readFileSync( 'test.txt', 'utf-8' ).trim().split( /\r?\n/ ).map( sim => sim.trim() );

	  x.forEach( async file => {

	    await new Promise( resolve => {

	      const f = `${process.cwd()}\\${file.split( '/' ).join( '\\' )}`.split( '\\' ).join( '\\\\' );
	      console.log( 'fixing', f );

	      const s = cp.spawn( 'bash' );
	      s.stdin.end( `grunt insert-require-statement --name=merge --file=${f}` );
	      s.once( 'exit', () => {
	        resolve();
	      } );
	    } );

	  } );
	  await execute( 'rm', [ 'test.txt' ], process.cwd() );
	} )();
   ```
	
6. Run `for-each.sh perennial/data/active-runnables "grunt lint"`
7. Run `for-each.sh perennial/data/active-runnables "git diff --name-only --staged | xargs git diff --name-only > test.txt && node ../sandbox/js.js"`. This script is responsible for gathering a list of files that have working copy changes in them, and running `grunt insert-require-statement` on them to add `merge` (via the node script).
8. Run aqua, and make sure all is well.

I ran this process for the sims I am responsible for, mainly as a test, and things went very well. In fact, the validation in `merge` fixed one spot in FPAF where we were passing a faulty arg in (see commit above in `WaterTowerScreenView`).

I am not recommending that anyone else do these steps, but I thought it was important to keep good notes. Likely I will try to convert other repos until we can think of a reason not too (i.e. see https://github.com/phetsims/phet-core/issues/73).

**Comment by zepumph** [comment]
Also note that I added a lint rule for this purpose, which supports the "fix" option, but I don't necessarily think it should stick around.

**Comment by zepumph** [comment]
I updated documentation in https://github.com/phetsims/phet-info/commit/0d075cb732fd0060ddf85661f6266b10d42ef6b8 and https://github.com/phetsims/phet-core/commit/ed3bb6bc8dd74666b7493f1258024ba900c190de 
![image](https://user-images.githubusercontent.com/6856943/66627148-3e5f2780-eba7-11e9-8d3d-d4260055ca94.png)

**Comment by zepumph** [comment]
@pixelzoom, after looking through #73, does the global replacement seem good for you?

**Comment by pixelzoom** [comment]
yes, commented in the issue and closed it.

**Comment by zepumph** [comment]
> In fact, the validation in merge fixed one spot in FPAF where we were passing a faulty arg in

Add one more to the bug catch count!

**Comment by pixelzoom** [comment]
That indicates that there is a missing test in mergeTest.  Should we correct that?

**Comment by zepumph** [comment]
I do not think so. It was a faulty usage, not faulty merge code.

**Comment by pixelzoom** [comment]
https://github.com/phetsims/phet-core/issues/74 is a prerequisite to global replacement of `_.extend` with `merge`.

**Comment by zepumph** [comment]
I'm in the process of fixing all active runnables not already touched currently, and it is going well. The scripts above are doing their job, and I will just make sure to test well, and monitor CT this afternoon. Commits likely coming soon.

**Comment by zepumph** [comment]
I made the changes, and then, while testing, had to fix a number of spots. Most of them were simple, but a few cases had a potential to change sim code, and so I want to make sure that the responsible dev can have a look at them, if there is a dev next to the item, please review the commit for that specific file and check it off if there aren't problems, then you can unassign yourself:

* HookesLawIconFactory.createTwoSpringsIcon()
* GraphingQuadratics.FocusAndDirectrixModel
* JoistButton
* PlayAreaNode
* MAL.CH4
* number line integers, NumberLineNode.handlePointAdded
* bendling light IntroScreen passing into IntroView
* SOM CAF BBS RS GlobalOptionsNode (MenuOptionsNode), this pattern included an extend when it didn't need it.
* GlobalOptionsNode
* equality explorer SolveItScreenView
* rename `validateOptions` Validator option to `validateValidator`

- [ ] KITE/LineStyles has an extra prototype on options sometimes, it is using `_.extend`. see https://github.com/phetsims/kite/issues/81
- [ ] CLB HingePointNode @Denz1994 
- [ ] BAAGameModel.emitCheckAnswer @jbphet 
- [ ] ESP(B)Sim.js @jessegreenberg  (both basics and regular may have been effected)

This has been done on all sim repos, and there are currently 39 usages of `_.extend` in our repos. For the most part, this is in chipper, perennial, and other node code. There are also some usages in places where we can't import `PHET_CORE/merge`.

CT will be a really great place to test this, because of how exhaustive it is, and most of these fail quickly and loudly. The above were the place caught while local fuzzing, but I will check in on CT soon.

**Comment by zepumph** [comment]
I also want to note that all the changes I did above felt like appropriate changes, like there were sneaky/lazy bugs in the code that where sitting there uncaught. `merge` caught them.

**Comment by pixelzoom** [comment]
I reviewed the changes to my sims (hookes-law, graphing-quadratics, equality-explorer) noted in https://github.com/phetsims/phet-core/issues/71#issuecomment-543412546. All looks well.  Thanks for handling this.

**Comment by pixelzoom** [comment]
Now that @zepumph has gone to the trouble of replacing `_.extend` with `merge` throughout, a couple of questions:

(1) Does this mean that `_.extend` is now verboten?

(2) If so, should `_.extend` be added to bad-text.js? If not, how do we prevent it from sneaking back in?

**Comment by zepumph** [comment]
>there are currently 39 usages of _.extend in our repos

This didn't count phet-io-wrapper-sonficiation, which I had converted accidentally and was causing errors.

**Comment by zepumph** [comment]
>(1) Does this mean that _.extend is now verboten?

That would be a great question for the options/config design pattern meeting. I'll mark https://github.com/phetsims/chipper/issues/805 for developer meeting, and see if we want to cover that in the pattern meeting.

**Comment by jbphet** [comment]
This was assigned to me to address a change from `extend` to `merge` in `BAAGameModel.emitCheckAnswer`.  When I looked at this code, it didn't appear at all familiar to me, so I checked the history of it.  Turns out it was added by @samreid in https://github.com/phetsims/build-an-atom/commit/81ebc9f7773a60953e2294b6a5d24609838c52d2.

@samreid - I'm turning this over to you to address, since it wasn't immediately obvious to me what the `extension` parameter was all about, so I couldn't make the determination about whether the change to `merge` could introduce any issues.

**Comment by samreid** [comment]
It looks like this code is not buggy:

```js
this.checkAnswerEmitter.emit( merge( extension || {}, arg ) );
```

but it would be clearer as 

```js
this.checkAnswerEmitter.emit( merge( arg, extension ) );
```

It looks like only `ToElementChallenge` provides the `emitMessageOptions`.

I tested this proposed change for a `ToElementChallenge` and another type of challenge to see how `merge` would deal with an undefined arg, and it had the expected behavior.

I'll commit this change and double check with @zepumph that `merge(options,undefined)` is an allowable call (and not expected to error out in the future).

**Comment by zepumph** [comment]
Thanks @samreid, that seems good to me, and source is allowed to be undefined (because options are optional). 

Pinging @Denz1994 and @jessegreenberg. Likely these are simple checks, but it would be good to have the responsible dev sign off before closing this.

**Comment by zepumph** [comment]
There is a no-extend lint rule that isn't turned on. I'm not sure how hard it would be to get this going in our post es6-modules. I'll take a look.

**Comment by zepumph** [comment]
This was covered by the bad-sim-text lint rule, so I deleted it.

**Comment by zepumph** [comment]
All that is left is a review on the sim-specific cases.

**Comment by jessegreenberg** [comment]
I reviewed https://github.com/phetsims/capacitor-lab-basics/commit/2493d0c8d94731f6fb21d6578151a5b78e11eec7 and HingePointNode looks good in that sim.

Usages in ESP are also good. Closing.
