### ISSUE TITLE
ignoreUndefined allocates extra Array in merge

### ISSUE THREAD

**Issue by zepumph** [phetsims/phet-core#73]
From slack @pixelzoom said:

>Chris Malley 17:53
Has someone checked whether merge and _.extend result in the same number of object allocations?  This line in merge looks suspect, as it will allocate a new object for every object in argument sources: (edited) 

>   `const ignoreUndefined = _.filter( sources, source => source !== undefined );`

**Comment by zepumph** [comment]
@pixelzoom does that seem better to you?

**Comment by pixelzoom** [comment]
Yes, replacing `_.filter` with an `if` statement eliminates the unnecessary allocations. 

I don't see any other unnecessary allocations, so closing.

**Comment by pixelzoom** [comment]
Reopening, this broken compatibility with `_.extend`.  See https://github.com/phetsims/phet-core/issues/74#issuecomment-541212657.

**Comment by zepumph** [comment]
Thanks. I think it will be solved over in https://github.com/phetsims/phet-core/issues/74. Closing
