### ISSUE TITLE
Delete PHET_CORE/extend

### ISSUE THREAD

**Issue by zepumph** [phetsims/phet-core#75]
Now that we have `merge`, and are converting all usages like in https://github.com/phetsims/phet-core/issues/71, should we delete this?

**Comment by jonathanolson** [comment]
`merge` in no way works with ES5 getters/setters nicely, or prototype-style objects, right? Any time PHET_CORE/extend is used, I would strongly presume we should NOT swap in `merge` since it would likely break things.

**Comment by zepumph** [comment]
Is that preferable to adding es5 getter support to merge?

**Comment by jonathanolson** [comment]
It would be possible to potentially add support to merge, but PHET_CORE/extend was really used for different things so I think it's fine to keep it and have it used for different things.

**Comment by zepumph** [comment]
That makes the most sense to me. I updated doc to specify this distinction. Does that feel good? Anything else here? Ready to close?

**Comment by jonathanolson** [comment]
Looks great, thanks!
