### ISSUE TITLE
Orientation should use rich enumerations

### ISSUE THREAD

**Issue by samreid** [phetsims/phet-core#78]
Orientation was developed with an older pattern for rich enumerations, now that we have Enumeration.byMap, it can be improved.  See https://github.com/phetsims/phet-core/issues/50 and https://github.com/phetsims/phet-core/issues/77.

**Comment by samreid** [comment]
I converted `Orientation` to use `Enumeration.byMap` in the above commit.  @jonathanolson can you please review at your convenience?

**Comment by jonathanolson** [comment]
Looks good to me, thanks!
