### ISSUE TITLE
Convert usages of inherit to use class

### ISSUE THREAD

**Issue by samreid** [phetsims/phet-core#82]
At today's dev meeting, we discussed that it would be very helpful to have Node.js as a `class` instead of `inherit`.  Some notes from discussion:

SR: Path to converting Node.js to es6?
CK: huge +1
JO: How about a semi-automated step that auto-converts everything?
CM: A main obstacle will be “this” before “super”

**Comment by samreid** [comment]
Or we could investigate making inherit able to extend classes.  @jonathanolson said he doesn't remember why that wasn't already supported, but pointed out that might work.

We could also do this manually as a chip-away, there are only 2000 occurrences or so.

**Comment by pixelzoom** [comment]
It might be nice to write a script/task that identifies "this before super" cases.  Then fix those before running an automated task that does conversion.

**Comment by samreid** [comment]
Maybe use Esprima as a parser step?

**Comment by pixelzoom** [comment]
Unassigning. All of my sims have already been converted to class (see https://github.com/phetsims/tasks/issues/1026), and I'm unlikely to have time to work on this.  Feel free to ping me for feedback.

**Comment by samreid** [comment]
I'm currently seeing 1676 occurrences of `import inherit`.

**Comment by samreid** [comment]
This sounds like a good long-term goal, but I'm not planning to work on it in the near future.  Self-unassigning for now.

**Comment by jbphet** [comment]
We discussed this in today's dev meeting and decided that we should convert sims from `inherit` to `class` when doing something major with them, such as adding phet-io, but not to do it proactively.  I'm going to do it for states-of-matter, but there is a separate issue for that, so I'm going to unassign myself from this one.

**Comment by samreid** [comment]
We are pursuing this in https://github.com/phetsims/tasks/issues/1051 and related issues.  Closing as duplicate.
