### ISSUE TITLE
merge makes many unnecessary function calls

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-core#84]
Noted while working on #83.

In merge.js, `validateMergableObject` consists entirely of assertions, so it does not need to be called unless assertions are enabled.

But in built versions and in unbuilt mode without `?ea`, `merge` is making multiple no-op function calls to `validateMergableObject`. `merge` contains an `_.eachLoop`, a `for in` loop, it calls `merge` recursively, and `validateMergableObject` contains a `forEach` loop.   So there are many function calls here that don't need to be made. 

Also, the correct spelling is "mergeable".

So:
- [x]  Rename  `validateMergableObject` to `assertIsMergeable`
- [x] Call it using `assert && assertIsMergeable( arg )`

**Comment by pixelzoom** [comment]
Given the number of times that we call `merge`, this seemed like an important optimization.  So I went ahead and did the work in the above commit.  Tested with unbuilt (ea, no ea) and built versions.

@zepumph would you mind reviewing, since you are one of the primary authors?

**Comment by pixelzoom** [comment]
Note that I also revised the assertion messages in `assertIsMergeable`:

```diff
-  'Object should be null or a truthy object that cannot have an extra prototype' );
+ 'object is not compatible with merge' );

- 'cannot use merge with a setter' );
+ 'cannot use merge with an object that has a setter' );

- 'cannot use merge with a getter' );
+ 'cannot use merge with an object that has a getter' );
```

**Comment by pixelzoom** [comment]
Hmm, maybe there's more redundancy.  Isn't line 40 redundant, because `sourceProperty` will be validated by the call to `merge` on line 41? 

```js
39            // ensure that the *Options property is a POJSO
40            assert && assertIsMergeable( sourceProperty );
41
41            target[ property ] = merge( target[ property ] || {}, sourceProperty );
```

**Comment by pixelzoom** [comment]
To check whether a `source` was being validated twice, I added 2 lines around `assertIsMergeable( source )`:

```
      assert && assert( !source.wasValidated, 'source was already validated' );
      assert && assertIsMergeable( source );
      source.wasValidated = true;
```

... and this fails.  So this call is indeed redundant, and has been removed in the above commit.

**Comment by pixelzoom** [comment]
Looks like unit tests are failing for phet-core, I'll check it out.

**Comment by pixelzoom** [comment]
I restored the `assertIsMergable( sourceProperty )` that I removed in https://github.com/phetsims/phet-core/commit/759202686989c9adc60e5ea298b3132aecd5f102.  But now I'm confused, because my test in https://github.com/phetsims/phet-core/issues/84#issuecomment-620273046 indicated that call is redundant.  @zepumph can you clarify for me?

**Comment by pixelzoom** [comment]
I'm going to label this issue as blocks-publication.  Since `merge` is so widely used, this work should not be deployed in a "partially done" state.

**Comment by zepumph** [comment]
The errored unit test you are running into is a bit of a middle group. 

In previous merge discussion we said that a source could be `undefined`, to support optional options objects, but we said, as the first point in https://github.com/phetsims/phet-info/issues/91#issuecomment-519652587, that we do not support that for `*Options` fields within options. Thus the unit tests represent the desired behavior, and thus we should try to improve the redundancy without changing the behavior. 


I'll poke around a bit.

**Comment by zepumph** [comment]
@pixelzoom, please review. I simplified the assertions, taking into account that *Options objects will be validated when it is recursively merged inside line 41. Thus, the only "special" validation to give to the `*Options` fields is to make sure that they aren't `undefined`. Unlike top level sources, we do not let that occur.

Thanks for working on the redundancy here, I think all the above commits are an improvement. Anything else here?

**Comment by pixelzoom** [comment]
Thanks @zepumph. Previous commit looks good. Closing.
