### ISSUE TITLE
Poolable should expose pool size and maximum size

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/phet-core#89]
In Slack:

> Jonathan Olson  12:50 PM
> My preference currently is a public getter for Vector2.poolSize (current size of the pool), and a public getter/setter for Vector2.maxPoolSize (backed by a setter function with assertions)
> 
> Chris Malley  12:50 PM
> That sounds nice.

**Comment by jonathanolson** [comment]
@pixelzoom committed above, can you try it out in your code?

**Comment by pixelzoom** [comment]
Implemented in Fourier, and it seems to be working as expected. See https://github.com/phetsims/fourier-making-waves/commit/0fef5870f848f8941182a1495cad92254f4764e4.

Thanks for the quick turnaround.  Anything else to do here?

**Comment by jonathanolson** [comment]
Nothing else, thanks! Closing.
