### ISSUE TITLE
Rename Enumeration->EnumerationDeprecated

### ISSUE THREAD

**Issue by zepumph** [phetsims/phet-core#95]
This strategy has been deprecated in https://github.com/phetsims/chipper/issues/1106. We instead want to use what is currently called RichEnumeration, which will be renamed to Enumeration as part of this issue.

**Comment by zepumph** [comment]
Beyond the basic renaming, here are the other thoughts that I have on this:

- ​[ ] Rename RichEnumeration-> Enumeration

- [ ] EnumerationProperty -> EnumerationDeprecatedProperty

- [ ] {Enumeration} seems buggy to me, should probably be {EnumerationDeprecated} for now, but eventually will just be the actual enumeration

- [ ] EnumerationDeprecatedIO?

- [ ] What is going on with EnumerationMap?

- [ ] EnumerationTests -> EnumerationDeprecatedTests

- [ ] What do do about both being called EnumerationIO?

This is all I could do for now, but I'll come back. Adding @samreid too in case he wants to keep cracking at it.

**Comment by samreid** [comment]
I also considered the possibility that we would delete the entire old Enumeration stack and port everything to use the proposed pattern.  For instance, converting one usage in Hooke's Law took a few minutes:

<details>

```diff

Index: js/energy/view/EnergyGraph.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/energy/view/EnergyGraph.js b/js/energy/view/EnergyGraph.js
--- a/js/energy/view/EnergyGraph.js	(revision a29ff367a9d55eca3d4144df28b827387ba3daed)
+++ b/js/energy/view/EnergyGraph.js	(date 1641521921551)
@@ -6,10 +6,16 @@
  * @author Chris Malley (PixelZoom, Inc.)
  */
 
-import EnumerationDeprecated from '../../../../phet-core/js/EnumerationDeprecated.js';
 import hookesLaw from '../../hookesLaw.js';
+import EnumerationValue from '../../../../phet-core/js/EnumerationValue.js';
+import RichEnumeration from '../../../../phet-core/js/RichEnumeration.js';
 
-const EnergyGraph = EnumerationDeprecated.byKeys( [ 'BAR_GRAPH', 'ENERGY_PLOT', 'FORCE_PLOT' ] );
+class EnergyGraph extends EnumerationValue {
+  static BAR_GRAPH = new EnergyGraph();
+  static ENERGY_PLOT = new EnergyGraph();
+  static FORCE_PLOT = new EnergyGraph();
+  static enumeration = new RichEnumeration( EnergyGraph );
+}
 
 hookesLaw.register( 'EnergyGraph', EnergyGraph );
 export default EnergyGraph;
\ No newline at end of file
Index: js/energy/view/EnergyViewProperties.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/energy/view/EnergyViewProperties.js b/js/energy/view/EnergyViewProperties.js
--- a/js/energy/view/EnergyViewProperties.js	(revision a29ff367a9d55eca3d4144df28b827387ba3daed)
+++ b/js/energy/view/EnergyViewProperties.js	(date 1641521887879)
@@ -7,7 +7,7 @@
  */
 
 import BooleanProperty from '../../../../axon/js/BooleanProperty.js';
-import EnumerationProperty from '../../../../axon/js/EnumerationProperty.js';
+import RichEnumerationProperty from '../../../../axon/js/RichEnumerationProperty.js';
 import HookesLawQueryParameters from '../../common/HookesLawQueryParameters.js';
 import ViewProperties from '../../common/view/ViewProperties.js';
 import hookesLaw from '../../hookesLaw.js';
@@ -23,7 +23,7 @@
     super( tandem );
 
     // @public which graph is visible
-    this.graphProperty = new EnumerationProperty( EnergyGraph, EnergyGraph.BAR_GRAPH, {
+    this.graphProperty = new RichEnumerationProperty( EnergyGraph.BAR_GRAPH, {
       tandem: tandem.createTandem( 'graphProperty' )
     } );
 
```

</details>

If it took 5 minutes to convert each one (optimistically), that would be 5 minutes * 200 cases = 16 hours.  Maybe too long to make it part of this effort?  But I thought I would bring it up as a possibility.

**Comment by zepumph** [comment]
In regards to https://github.com/phetsims/phet-core/issues/95#issuecomment-1007088514, I think it is a possibility, but most likely to just convert common code and heavily used cases. It seems like a few too many usages to convert fully.

**Comment by zepumph** [comment]
This has been completed. @samreid can you please glance through this work along with everything else. Failures should most likely be pretty loud, and type checking and lint was working.

**Comment by samreid** [comment]
I spot checked a few places and didn't see any trouble.  CT hasn't indicated problems related to this.  Closing.
