### ISSUE TITLE
Handle EnumerationIO and EnumerationDeprecatedIO

### ISSUE THREAD

**Issue by zepumph** [phetsims/phet-core#97]
From working on renaming in https://github.com/phetsims/phet-core/issues/95

Steps for this issue:
* Both EnumerationDeprecatedIO and "RichEnumerationIO" (soon to be EnumerationIO), will have the type name `EnumerationIO`. 
* Make them share or know about each other's cache, and assert that phetioDocumentation is not different if they share the same type name. 
* Look into combining files to see if it makes sense or is possible. 

We don't think it will cause complications with PhET-iO to have them share the same name for PhET-iO because each IOType is parametrized on the actual instance of enumeration, so we know the right values will be given by the PhET-iO system.

**Comment by zepumph** [comment]
- [ ] Move this IO type to tandem from axon. It can't be in phet-core because it relies on tandem.

**Comment by zepumph** [comment]
Alright, with only a limited addition of API in EnumerationDeprecated, I was able to consolidate EnumerationIO types. There is now just a single IOType, in tandem, that both EnumerationDeprecated and Enumeration use.

**Comment by zepumph** [comment]
Most important for the review @samreid: will you please make sure that the changes to ts-config files are as expected. I exclusively removed include/exclude paths, but they all seemed like workarounds, so I hope all is well here!

**Comment by samreid** [comment]
I reviewed all the commits and didn't see any problems.  I skimmed the changes in tsconfig files and they seem reasonable.  I think `tsc` would have told us if some file was out of scope.  Can this issue be closed.
