### ISSUE TITLE
Is EnumerationValue.isEnumerationValue still needed?

### ISSUE THREAD

**Issue by zepumph** [phetsims/phet-core#98]
I think this may be obsolete since adding a bit more structure to EnumerationValue. I'll take a look.

From https://github.com/phetsims/chipper/issues/1106

**Comment by zepumph** [comment]
@samreid, I didn't see any type errors here, do you think we are good to close this issue?

**Comment by samreid** [comment]
We needed `isEnumerationValue` when `EnumerationValue` read:

```ts
class EnumerationValue {
  name?: string; // undefined until set by RichEnumeration

  toString() {
    return this.name;
  }
}
```

So I think we may still need it.  But I tried deleting the body of EnumerationValue to try to reproduce the problem we saw before, and I couldn't recall the context.

**Comment by zepumph** [comment]
I thought that name, enumeration, and sealedCache would now be enough to structurally type this unique class. I'm glad you can't reproduce the original issue. Please reopen if you have any other thoughts.

**Comment by samreid** [comment]
`name` and `enumeration` are both optional, so objects without those will match the interface.  The `sealedCache` is `static` so it doesn't appear in the `EnumerationValue` interface.

**Comment by zepumph** [comment]
Ahh, thanks. Yes that makes perfect sense. Reverted above. Closing.
